### PR TITLE
Avoid circular references in Serial Mode in Tango (Issue 846)

### PR DESCRIPTION
**Pull request by reszelaz**
This tests demonstrate #846, so they should fail currently.

### CODE REVIEW

**Comment by cpascual** [comment]
Thanks for the tests!
In order to not introduce failures on other developments, I propose to re-purpose this PR to include the fix as well as the tests, and integrate it only once the tests are passing

**Comment by reszelaz** [comment]
Not sure why, but tests on py2 still fails but on py3 works well..

**Comment by cpascual** [comment]
We identified the problem in the testsuite as a contamination from the GUI tests. it can be reproduced with:

```console
:~/src/taurus/lib/taurus(reszelaz-test-tangofactory)$ python -m unittest taurus.qt.qtgui.display.test.test_tauruslabel.Bug169_Test.test_bug169 taurus.core.tango.test.test_tangofactory
MainThread     INFO     2019-01-28 11:30:18,629 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2019-01-28 11:30:18,768 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/icon/)
MainThread     WARNING  2019-01-28 11:30:19,061 TaurusRootLogger: /nfs/home/cpascual/src/taurus/lib/taurus/core/tango/test/test_tangofactory.py:31: DeprecationWarning: taurus.external.unittest is deprecated since 4.3.2. Use unittest instead
  from taurus.external.unittest import TestCase

MainThread     WARNING  2019-01-28 11:30:19,347 b'TaurusLabel.sys/tg_test/1/double_scalar#label': /nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/base/taurusbase.py:1414: DeprecationWarning: setUseParentModel(True) is deprecated since 4.3.2. Use explicit models including the parent model instead
  TaurusBaseComponent.setUseParentModel(self, yesno)

.F.F
======================================================================
FAIL: test_attribute (taurus.core.tango.test.test_tangofactory.TestFactoryGarbageCollection)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nfs/home/cpascual/src/taurus/lib/taurus/core/tango/test/test_tangofactory.py", line 61, in test_attribute
    self.assertEqual(len(taurus.Factory().tango_attrs), 0, msg)
AssertionError: factory is polluted with attribute: [u'tango://controls02.cells.es:10000/sys/tg_test/1/state', u'tango://controls02.cells.es:10000/sys/tg_test/1/double_scalar']

======================================================================
FAIL: test_device (taurus.core.tango.test.test_tangofactory.TestFactoryGarbageCollection)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nfs/home/cpascual/src/taurus/lib/taurus/core/tango/test/test_tangofactory.py", line 52, in test_device
    self.assertEqual(len(taurus.Factory().tango_devs), 0, msg)
AssertionError: factory is polluted with device: [u'tango://controls02.cells.es:10000/sys/tg_test/1']

----------------------------------------------------------------------
Ran 4 tests in 0.340s

FAILED (failures=2)

```

**Comment by reszelaz** [comment]
Since the GUI tests are leaving the factory polluted I changed the strategy of the tests. Now they check the factory length increment. Also to not interfere with other models, the tests creates their own device.
With this the tests now work in all the cases.

**Comment by cpascual** [comment]
Thx!

Merged. I just commented out a test that was not currently checking anything.

**Pull request merged**
