### PR TITLE
Expression 'x' in Enumeration fails on python3 with KeyError.

### PR DESCRIPTION
**Pull request by asenchenko**
To solve this problem, explicit __contains__ method is added.

### CODE REVIEW

**Comment by cpascual** [comment]
Hi @asenchenko , I am surprised by this PR since Taurus does not support python 3 yet (see #680 ), although some effort has been started (see #703)
So, I wonder... are you using it (or some part of it) under python3 ? 
If so, could you give some details?
Also, you probably could join the conversation in #703 and contribute there (help is needed!)

Apart from that, since your commit is about `taurus.core.util.enumeration.Enumeration`, I think you should also be aware of [SEP12](http://www.sardana-controls.org/sep/?SEP12.md). While this is not officially implemented (we haven't implemented the backwards compatibility layer), in practice we try to follow it for new developments (i.e., **we try to base all new enumerations on the `Enum` module rather than on `taurus.core.util.enumeration.Enumeration`**)

Having said all that, I've revised your proposed changes and they all seem ok to me, so IMHO we can merge it, but before, could you please provide some code snippet demonstrating the intended feature/bugfix that it provides?

**Comment by asenchenko** [comment]
Hi @cpascual. I'm sorry for the confusion. I know that Taurus does not support python3.
I'm porting Taurus to python3 and this bug appeared during this work. 
It fixes problem with enums in #703.

**Comment by cpascual** [comment]
> I'm porting Taurus to python3 and this bug appeared during this work. It fixes problem with enums in #703.

Ok, then I wonder if it wouldn't make more sense to make a PR against the branch of #703 ? (just to centralise the python3-related effort and avoid merge conflicts due to parallel implementations).

However, for that we need to know if @piertoni is still interested in this... I'll ask in #703

**Comment by cpascual** [comment]
Hi, I merged these changes into the branch for #703, and therefore I am closing this PR to centralise the discussion on #703 and #680

**Pull request closed without merging**
