### PR TITLE
Fixing TaurusLed handling of spectrum attributes.

### PR DESCRIPTION
**Pull request by mkomel**
This proposal fixes TaurusLed handling of spectrum boolean attributes, which was broken by the following commit (from November 2017):
[eb17e2ed33195bf08aa57673fe0f40016ffdeb87](https://github.com/taurus-org/taurus/commit/eb17e2ed33195bf08aa57673fe0f40016ffdeb87)

See also comment under the above commit for detailed explanation of the problem.

### CODE REVIEW

**Comment by cpascual** [comment]
Hi, thanks for the proposed fix, but I see some issues with the implementation:
- using `type(foo) == sometype` is discouraged (using isinstance instead is slightly better, but even that should be avoided in favour of [ducktyping](https://en.wikipedia.org/wiki/Duck_typing) whenever possible)
- the conversion should not only be done for `int`. In fact, IMHO, a cast to bool should be done in all cases, and the support for non-scalar attributes should be based on applying the modelIndex slicing before the cast

**Comment by mkomel** [comment]
Agreed, commited alternative solution, taking into account your comments.

**Comment by mkomel** [comment]
This fix has not been merged yet.. 

Since the problem still exists in the latest release, could you please consider merging it?

**Comment by cpascual** [comment]
Hi @mkomel:  sorry for the delay. I get into re-reviewing it right now...

**Comment by cpascual** [comment]
All ok for me. Merging. Thanks for contributing, and sorry again for the delay in reviewing.

Cheers!

**Pull request merged**
