### PR TITLE
fix _info due to Unpacking error

### PR DESCRIPTION
**Pull request by piertoni**
On Windows platform causes unpacking error as an additional parameter is delivered, in this case is 'Starter', as I don't know the rest of the code I have assigned a temporary name that should be changed with the appropriated name.
I found this error using taurusgui --new-gui on Model Choser, without this was causing unpacking error, with this additional parameter it seems to work

### CODE REVIEW

**Comment by cpascual** [comment]
Hi @piertoni ,
Thanks for the pull request. In order to facilitate the investigation of the cause, could you please provide us with step-by-step instructions on how to reproduce your problem?

**Comment by piertoni** [comment]
Launch taurusgui --new-gui
on Monitor List click on Browse
and than the Unpacking Error,
here is a print from _INFO, you can see that has 8 arguments and from this gives unpacking error.
['dserver/databaseds/2', 'IOR:010000001700000049444c3a54616e676f2f4465766963655f353a312e3000000100000000000000b1000000010102000b0000003137322e31372e302e3300001027000014000000647365727665722f646174616261736564732f320300000000000000080000000100000000545441010000001c000000010000000100010001000000010001050901010001000000090101000254544141000000010000000d00000063623534333535313733656400000000250000002f746d702f6f6d6e692d74616e676f2f3030303030303031362d3134393031393038313500', '5', 'DataBaseds/2', 'cb54355173ed', '22nd March 2017 at 13:53:35', '?', 'DServer']
['dserver/nemo/istanza', 'IOR:010000001700000049444c3a54616e676f2f4465766963655f343a312e3000000100000000000000b0000000010102000d0000003139322e3136382e302e333300002baa0e000000fe8ee7dc5800004ffb000000000100000300000000000000080000000100000000545441010000001c000000010000000100010001000000010001050901010001000000090101000254544144000000010000000f0000006964652d5669727475616c426f780000280000002f746d702f6f6d6e692d7070616e63696e6f2f3030303032303437352d3134393038373232303600', '4', 'NEMO/istanza', 'ide-virtualbox', '31st March 2017 at 06:05:51', '30th March 2017 at 09:48:57', 'DServer']
['dserver/starter/cb54355173ed', 'IOR:010000001700000049444c3a54616e676f2f4465766963655f353a312e3000000100000000000000ad000000010102000b0000003137322e31372e302e330000a9d300000e000000fedf81d25800000011000000000100000300000000000000080000000100000000545441010000001c000000010000000100010001000000010001050901010001000000090101000254544141000000010000000d00000063623534333535313733656400000000250000002f746d702f6f6d6e692d74616e676f2f3030303030303031372d3134393031393038313500', '5', 'Starter/cb54355173ed', 'cb54355173ed', '22nd March 2017 at 13:53:40', '?', 'DServer']
['dserver/tangoaccesscontrol/1', 'IOR:010000001700000049444c3a54616e676f2f4465766963655f353a312e3000000100000000000000ad000000010102000b0000003137322e31372e302e3300006dba00000e000000fee081d2580000003c000000000100000300000000000000080000000100000000545441010000001c000000010000000100010001000000010001050901010001000000090101000254544141000000010000000d00000063623534333535313733656400000000250000002f746d702f6f6d6e692d74616e676f2f3030303030303036302d3134393031393038313600', '5', 'TangoAccessControl/1', 'cb54355173ed', '22nd March 2017 at 13:53:36', '?', 'DServer']
['dserver/tangotest/test', 'IOR:010000001700000049444c3a54616e676f2f4465766963655f353a312e3000000100000000000000ad000000010102000b0000003137322e31372e302e330000c68b00000e000000fee081d2580000003d000000000100000300000000000000080000000100000000545441010000001c000000010000000100010001000000010001050901010001000000090101000254544141000000010000000d00000063623534333535313733656400000000250000002f746d702f6f6d6e692d74616e676f2f3030303030303036312d3134393031393038313600', '5', 'TangoTest/test', 'cb54355173ed', '22nd March 2017 at 13:53:36', '?', 'DServer']
['supply/impianti/fm', 'IOR:010000001700000049444c3a54616e676f2f4465766963655f343a312e3000000100000000000000b0000000010102000d0000003139322e3136382e302e333300002baa0e000000fe8ee7dc5800004ffb000000000000000300000000000000080000000100000000545441010000001c000000010000000100010001000000010001050901010001000000090101000254544144000000010000000f0000006964652d5669727475616c426f780000280000002f746d702f6f6d6e692d7070616e63696e6f2f3030303032303437352d3134393038373232303600', '4', 'NEMO/istanza', 'ide-virtualbox', '31st March 2017 at 06:05:51', '30th March 2017 at 09:48:57', 'NEMOD4Le']
['sys/access_control/1', 'IOR:010000001700000049444c3a54616e676f2f4465766963655f353a312e3000000100000000000000ad000000010102000b0000003137322e31372e302e3300006dba00000e000000fee081d2580000003c000000000000000300000000000000080000000100000000545441010000001c000000010000000100010001000000010001050901010001000000090101000254544141000000010000000d00000063623534333535313733656400000000250000002f746d702f6f6d6e692d74616e676f2f3030303030303036302d3134393031393038313600', '5', 'TangoAccessControl/1', 'cb54355173ed', '22nd March 2017 at 13:53:36', '?', 'TangoAccessControl']
['sys/database/2', 'IOR:010000001700000049444c3a54616e676f2f4465766963655f353a312e3000000100000000000000a5000000010102000b0000003137322e31372e302e330000102700000800000064617461626173650300000000000000080000000100000000545441010000001c000000010000000100010001000000010001050901010001000000090101000254544141000000010000000d00000063623534333535313733656400000000250000002f746d702f6f6d6e692d74616e676f2f3030303030303031362d3134393031393038313500', '5', 'DataBaseds/2', 'cb54355173ed', '22nd March 2017 at 13:53:35', '?', 'DataBase']
['sys/tg_test/1', 'IOR:010000001700000049444c3a54616e676f2f4465766963655f353a312e3000000100000000000000ad000000010102000b0000003137322e31372e302e330000c68b00000e000000fee081d2580000003d000000000000000300000000000000080000000100000000545441010000001c000000010000000100010001000000010001050901010001000000090101000254544141000000010000000d00000063623534333535313733656400000000250000002f746d702f6f6d6e692d74616e676f2f3030303030303036312d3134393031393038313600', '5', 'TangoTest/test', 'cb54355173ed', '22nd March 2017 at 13:53:36', '?', 'TangoTest']
['tango/admin/cb54355173ed', 'IOR:010000001700000049444c3a54616e676f2f4465766963655f353a312e3000000100000000000000ad000000010102000b0000003137322e31372e302e330000a9d300000e000000fedf81d25800000011000000000000000300000000000000080000000100000000545441010000001c000000010000000100010001000000010001050901010001000000090101000254544141000000010000000d00000063623534333535313733656400000000250000002f746d702f6f6d6e692d74616e676f2f3030303030303031372d3134393031393038313500', '5', 'Starter/cb54355173ed', 'cb54355173ed', '22nd March 2017 at 13:53:40', '?', 'Starter']

**Comment by cpascual** [comment]
Hi @piertoni , I cannot reproduce the problem.
I tried with Taurus4 on a win7 (with Tango8) and on a debian9 (with Tango9). What OS and versions of Taurus, Tango and PyTango do you have?

Can you please try the following code in your machine and paste the result?

```python
import taurus
db = taurus.Authority()
info = db.command_inout("DbGetDeviceInfo", 'sys/tg_test/1')[1]
print len(info), info
```

Also,
The part of the code that you are having trouble with is an non-optimized fallback that should only kick-in if you are not using a mysql DB. Are you by any chance using a sqlite DB?
If not, there may be some bug in Taurus, ...or something changed in PyTango

Finally:
In any case, IMHO, a better solution for this problem (instead of adding another variable for unpack) would be to do something like:

```python
name, ior, level, server, host, started, stopped = _info[:7]
```

(this way it is safe for the cases where len(_info)==7 and for len(_info)==8 )

**Comment by piertoni** [comment]
This is the result

`8 ['sys/tg_test/1', 'IOR:010000001700000049444c3a54616e676f2f4465766963655f353a312e3000000100000000000000ad000000010102000b0000003137322e31372e302e320000aeb200000e000000fe60d10d5900000042000000000000000300000000000000080000000100000000545441010000001c000000010000000100010001000000010001050901010001000000090101000254544141000000010000000d00000063623534333535313733656400000000250000002f746d702f6f6d6e692d74616e676f2f3030303030303036362d3134393430373737393200', '5', 'TangoTest/test', 'cb54355173ed', '6th May 2017 at 13:36:32', '24th April 2017 at 09:26:43', 'TangoTest']`

Taurus v. 4.0.3
Windows 7
Python 2.7
Tango on other machine launched by docker machine https://tango-controls/docker-mysql.git
MySql on other machine launched by docker machine https://tango-controls/tango-cs-docker.git

I agree with your unpacking solution:

`name, ior, level, server, host, started, stopped = _info[:7]`

**Comment by cpascual** [comment]
Hi, @piertoni 
Would you mind to submit another PR with the agreed solution?

**Comment by cpascual** [comment]
No reply from @piertoni. I am creating the new PR myself so that we do not forget it

**Pull request closed without merging**
