### PR TITLE
Fix regressions in Synoptics

### LINKED ISSUE #244: [Taurus4] Synoptic scalar viewer shows duplicate units
The scalar view of a jdraw_synoptic viewer shows duplicated  units, and also ignores the `unitVisible=False` property

To reproduce:

~~~
cd <taurus>/qt/qtgui/graphic/jdraw
python jdraw_view test/res/SimpleScalarViewer.jdw
~~~

Compare with [this snapshot](https://sourceforge.net/p/tauruslib/tickets/_discuss/thread/0616eb12/f233/attachment/Screenshot%20from%202014-03-10%2013%3A46%3A48.png)  for an example of how it should render

Reported by: cpascual ( http://sf.net/u/cpascual )

### LINKED ISSUE #360: TaurusJDrawSynopticView fails to update values (Taurus4 regression)
On Windows machine with Taurus 4.0.1

It seems if I don't click on the synoptic my objects aren't updated. It's a simple synoptic with just a background image and less than 10 basic forms.

### PR DESCRIPTION
**Pull request by cpascual**
This PR fixes two regressions in Taurus 4 related to synoptics.

- Fix #360 Synoptic values not updated
- Fix #244 Units are duplicated in synoptic items

### CODE REVIEW

**Comment by cpascual** [comment]
While working on #360 I found the solution to the #244, which affects the same widget, so I included it in this PR and edited its text accordingly

**Comment by cpascual** [comment]
Can some of @taurus-org/integrators review this?

**Comment by teresanunez** [comment]
I start to review it

**Comment by teresanunez** [comment]
It solves #360 and #244. I merge it. Carlos, many thanks.

**Pull request merged**
