### PR TITLE
Proposing fix for issue #648 (taurusLabel.setModelIndex() not working).

### PR DESCRIPTION
**Pull request by mkomel**
Fix is really simple, instead of calling getDisplayValue on the label it should be done on "self", so that it ends up in TaurusScalarAttributeControllerHelper.getDisplayValue, where the modelIndex handling is implemented.

### CODE REVIEW

**Comment by mkomel** [comment]
Fixes #648

**Comment by cpascual** [comment]
Ho, thanks a lot for the proposed fix.

Unfortunately, this fix breaks some functionality (the support for fragments):

For example, this code raises an AttributeError:
```python
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.display import TaurusLabel

if __name__ == '__main__':
    import sys
    app = TaurusApplication()
    w = TaurusLabel()
    model = 'bl97/tangotest/1/float_scalar#label'
    w.setModel(model)
    w.show()
    sys.exit(app.exec_())
```

I am looking into it to try to find a solution

**Comment by cpascual** [comment]
Note. This PR was based on an old-ish checkout (previous to the integration of #564).
I am merging the latest develop into this PR (and we will see that the unit tests are no longer passing)

**Comment by cpascual** [comment]
I am surprised that the Travis tests appear green. This worries me because locally they fail:

```
 :...taurus(mkomel-develop)$  python -m unittest -v taurus.qt.qtgui.display.test.test_tauruslabel` 

(...)
Ran 35 tests in 99.831s
FAILED (failures=3, errors=8)
```

Looking at the [line 4813 of the logs](https://travis-ci.org/taurus-org/taurus/jobs/341365584#L4813), I see: 
```
$ travis_wait docker exec -t taurus-test /bin/bash -c "TAURUS_STARTER_WAIT=5 taurustestsuite -e 'taurus\.core\.util\.test\.test_timer'"
Still running (1 of 20): docker exec -t taurus-test /bin/bash -c TAURUS_STARTER_WAIT=5 taurustestsuite -e 'taurus\.core\.util\.test\.test_timer'
The command docker exec -t taurus-test /bin/bash -c TAURUS_STARTER_WAIT=5 taurustestsuite -e 'taurus\.core\.util\.test\.test_timer' exited with 0.
Log:
/home/travis/.travis/job_stages: line 169:  4725 Terminated              travis_jigger $! $timeout $cmd
The command "travis_wait docker exec -t taurus-test /bin/bash -c "TAURUS_STARTER_WAIT=5 taurustestsuite -e 'taurus\.core\.util\.test\.test_timer'"" exited with 0.
```

And the bit about `/home/travis/.travis/job_stages: line 169:  4725 Terminated              travis_jigger $! $timeout $cmd` worries me (maybe we are silently ignoring test failures in travis now?)

**Comment by mkomel** [comment]
By looking a bit further, the controller that the tauruslabel uses in case when fragments are used seems to be of type TaurusConfigurationControllerHelper. This controller expects getModelFragmentName to exist on the widget, but TaurusLabel does not have it.

Since there is no widget in taurus that actually has getModelFragmentName function, I think it must have been a mistake during some past refactoring to not align this with what the widgets have (e.g. either use modelFragmentName field on the widgets, either add function getModelFragmentName on the widgets). 

I have made a commit with the first solution (changing a call .getModelFragmentName() to .modelFragmentName)

**Comment by mkomel** [comment]
In order for fragments like att_name#rvalue.units  to work, additional change had to be made (previous commit).

Note that some tauruslabel tests still fail, however I don't really understand why those tests are written as they are:
as one example: 
```
@insertTest(helper_name='checkFormat',
                    model='eval:Q("5m")#rvalue.units',
                    formatter=baseFormatter2,
                    expected="Unit")
```
Why would the above test expect "Unit"? If I use this model in code, it shows 'm' as one would expect, and not 'Unit'.

**Comment by mkomel** [comment]
Ok, this seems to do it (commit #b456fb1). Formatting of the value created in TaurusConfigurationControllerHelper is now delegated to the widget (actually very similar to what and how it is done in TaurusBase.getDisplayValue, which is where the code goes prior to my proposed fix).
The tests now pass.

It seems to me that there is some duplication or ambiguity in general in code around TaurusLabel - should it use stuff from the TaurusXXXControllerHelper(s) or stuff from TaurusBase? There are things that are implemented properly in one and not the other, and vice versa. For example, modelIndex handling was done in TaurusXXXControllerHelper, while fragments support and formatting in TaurusBase.  I guess the code should be merged somehow (e.g. to have a common implementation of features for widgets in one place).

**Comment by cpascual** [comment]
> The tests now pass.

Some tests are still failing on my machine.

```
$ python -m unittest -v taurus.qt.qtgui.display.test.test_tauruslabel.TaurusLabelTest2
(...)
======================================================================
FAIL: test_text_2 (taurus.qt.qtgui.display.test.test_tauruslabel.TaurusLabelTest2)
Testing text(expected='double_scalar', model='tango:TangoSchemeTest/unittest/temp-1/double_scalar', fgRole='label')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nfs/home/cpascual/src/taurus/lib/taurus/test/base.py", line 113, in newTest
    return helper(**helper_kwargs)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/display/test/test_tauruslabel.py", line 157, in text
    self.assertEqual(got, expected, msg)
AssertionError: wrong text for "tango:TangoSchemeTest/unittest/temp-1/double_scalar":
 expected: double_scalar
 got: 1.23 mm

======================================================================
FAIL: test_text_3 (taurus.qt.qtgui.display.test.test_tauruslabel.TaurusLabelTest2)
Testing text(expected='double_scalar', model='tango:TangoSchemeTest/unittest/temp-1/double_scalar#rvalue', fgRole='label')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nfs/home/cpascual/src/taurus/lib/taurus/test/base.py", line 113, in newTest
    return helper(**helper_kwargs)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/display/test/test_tauruslabel.py", line 157, in text
    self.assertEqual(got, expected, msg)
AssertionError: wrong text for "tango:TangoSchemeTest/unittest/temp-1/double_scalar#rvalue":
 expected: double_scalar
 got: 1.23 mm

======================================================================
FAIL: test_text_7 (taurus.qt.qtgui.display.test.test_tauruslabel.TaurusLabelTest2)
Testing text(expected='ATTR_VALID', model='tango:TangoSchemeTest/unittest/temp-1/double_scalar', maxdepr=1, fgRole='quality')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nfs/home/cpascual/src/taurus/lib/taurus/test/base.py", line 113, in newTest
    return helper(**helper_kwargs)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/display/test/test_tauruslabel.py", line 157, in text
    self.assertEqual(got, expected, msg)
AssertionError: wrong text for "tango:TangoSchemeTest/unittest/temp-1/double_scalar":
 expected: ATTR_VALID
 got: 1.23 mm

======================================================================
FAIL: test_text_9 (taurus.qt.qtgui.display.test.test_tauruslabel.TaurusLabelTest2)
Testing text(expected='0.00 mm', model='tango:TangoSchemeTest/unittest/temp-1/double_scalar', maxdepr=1, fgRole='w_value')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nfs/home/cpascual/src/taurus/lib/taurus/test/base.py", line 113, in newTest
    return helper(**helper_kwargs)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/display/test/test_tauruslabel.py", line 157, in text
    self.assertEqual(got, expected, msg)
AssertionError: wrong text for "tango:TangoSchemeTest/unittest/temp-1/double_scalar":
 expected: 0.00 mm
 got: 1.23 mm

----------------------------------------------------------------------
Ran 14 tests in 32.052s

FAILED (failures=4)

```

**Comment by cpascual** [comment]
> It seems to me that there is some duplication or ambiguity in general in code around TaurusLabel - should it use stuff from the TaurusXXXControllerHelper(s) or stuff from TaurusBase? There are things that are implemented properly in one and not the other, and vice versa. For example, modelIndex handling was done in TaurusXXXControllerHelper, while fragments support and formatting in TaurusBase. I guess the code should be merged somehow (e.g. to have a common implementation of features for widgets in one place).

You are 100% right. The `*ControllerHelper` stuff is there for historical reasons (they where an attempt at generalization that was never further developed) and IMHO we should eventually get rid of them by refactoring and simplifying the display widgets.

**Comment by mkomel** [comment]
I overlooked those TestSchemeTest tests.. I have done some additional changes, now the tests truly should pass.
I made changes to tauruscontroller.py (adding fragmentName to functions), then also had to tweak the overriden function signature in tauruslcd.py, in order to not break that widget.

Overall, it now works (as far as I can see), but it feels just a bit hacked up. I'm wondering whether it would make more sense to just implement modelindex handling in taurusbase  (maybe something to note down as a comment somewhere in code?) Especially since you are saying that you plan to get rid of the *ControllerHelper classes at some point..
But anyway, since the current solution seem to work I would stick with it for now.

**Comment by cpascual** [comment]
I just brought the latest changes from develop that fix the travis unittest issues detected in this PR before (see #683).

**Comment by mkomel** [comment]
I have now reverted the changes and instead done the modelindex handling in taurusbase.py.
This seems like a cleaner solution, the tests now also pass.

**Comment by cpascual** [comment]
I think everything is ok now (I just pushed a couple of minor changes to your last commit). 
Merging into develop.
Thanks @mkomel for the contribution (it wasn't an easy part of Taurus you got involved with!)  ;)

**Comment by CorF4** [comment]
Hello all,
coming back to this: I noticed that there is a problem with tango attributes in getDisplayValue() if the attribute quality is ATTR_INVALID (that is, we use push_change_event with attribute quality as argument). It seems that in this case ` v` is` []`, which is not `None` but the `idx` will then be out of range, so we need a protection against that: I propose to use simply (in taurusbase.py, lines 831 following):

```
        idx = self.getModelIndexValue()
        if v is not None and idx:
            if len(v):
                for i in idx:
                    v = v[i]
            else:
                return self.getNoneValue()
```

**Comment by cpascual** [comment]
I think that it is better (clearer and more efficient) to protect with a try-except.

**Comment by CorF4** [comment]
I agree with the try-except block, but I think we cannot simply write v = v[idx]: I see that in the case we have a string spectrum attribute we have tuples here and if I use your proposal the fields constantly show the none-value. Only idea I have is to use `v = v[idx[0]]` instead of the for-loop.

**Comment by cpascual** [comment]
> in the case we have a string spectrum attribute we have tuples here and if I use your proposal the fields constantly show the none-value. 

You are right. my proposed code only makes sense if both v and idx are numpy arrays. 

> Only idea I have is to use v = v[idx[0]] instead of the for-loop.

I think that to be closer to the behaviour of the previous implementation (loop)  the correct thing would be:
`v = v[idx[-1]] `

> I could do a pull-request: do I have permission to create a branch?

In Taurus we use the fork-and-pull workflow (see https://github.com/taurus-org/taurus/blob/develop/CONTRIBUTING.md ) so you do not need permission in the official repo to do a PR.

**Comment by CorF4** [comment]
Ok, thanks. Pull request is submitted  here #729.

**Pull request merged**
