### PR TITLE
Remove from Taurus objects the direct Logger dependence (TEP8)

### PR DESCRIPTION
**Pull request by cmft**
Remove from Taurus objects the direct Logger dependence

### CODE REVIEW

**Comment by cpascual** [comment]
This is currently breaking the tests. Please have a look at:
https://travis-ci.org/taurus-org/taurus/builds/177951399

**Comment by cpascual** [comment]
Note that the current implementation is not backwards compatible in general (not all of the members of the Logger class previously available are accessible in the new implementation).

So, either we find a way to code a fully compatible implementation, or we should re-evaluate the gains from this TEP.

**Comment by cmft** [comment]
I agree. I did an investigation about it, and I think that I found an option to do not break the old code.
See it [here](https://gist.github.com/cmft/5994c59d9614fdb4dee3d50754e203a4). What do you think @cpascual?

**Comment by cpascual** [comment]
After talking to @cmft , we decided to "stop pretending" and close this PR. The TEP8 would need a full reimplementation, but all work on that area has been stalled for too long since it fell from our priority list. We may re-take the implementation of TEP8 at some later time if it goes up in our (or someone else's) priority list again.

**Pull request closed without merging**
