### PR TITLE
Fix TaurusLCD bugs

### LINKED ISSUE #194: TaurusLCD represents only LAST digits of long numbers
Reproduced both in develop and taurus4

To reproduce, run:

```
from taurus.qt.qtgui.panel import TaurusForm
from taurus.qt.qtgui.application import TaurusApplication
import sys

app = TaurusApplication()

w = TaurusForm()

w.setModel(['eval:1.23456789', 'eval:1.23456789'])
w[0].setReadWidgetClass('TaurusLCD')
w.show()
sys.exit(app.exec_())
```

The LCD will only show "456789" which is misleadding, specially on floating point numbers

Reported by: cpascual ( http://sf.net/u/cpascual )

### LINKED ISSUE #463: TaurusLCD not working with Tango Attributes
The following code shows taurusLCD working for eval but not for Tango.

GUESS: this may be related to the changes done in #444

```python
from taurus.qt.qtgui.panel import TaurusForm
from taurus.qt.qtgui.application import TaurusApplication
import sys

app = TaurusApplication()

w = TaurusForm()

w.setModel(['eval:Q(1.23, "m")', 'tango:sys/tg_test/1/double_scalar',])
w[0].setReadWidgetClass('TaurusLCD')
w[1].setReadWidgetClass('TaurusLCD')
w.show()
sys.exit(app.exec_())
```

### PR DESCRIPTION
**Pull request by cmft**
Fix #194: TaurusLCD represents only LAST digits of long numbers 
Fix #463: TaurusLCD not working with Tango Attributes

### CODE REVIEW

**Comment by teresanunez** [comment]
Hi @cmft, I have checked this. #463 and #194 issues are both solved, but what I have found is that format is now not working propertly. If I try the script:


from taurus.qt.qtgui.panel import TaurusForm
from taurus.qt.qtgui.application import TaurusApplication
import sys

app = TaurusApplication()

w = TaurusForm()
w.setModifiableByUser(True)

from taurus.qt.qtgui.display import TaurusLCD
TaurusLCD.FORMAT = '{:.2f}'

w.setModel(['eval://Q(1.23456789, "m")', 'eval://1.23456789',])
w[0].setReadWidgetClass('TaurusLCD')
w[1].setReadWidgetClass('TaurusLCD')
w.show()
sys.exit(app.exec_())

The display of  'eval://1.23456789' uses the format '{:.2f}', but
['eval://Q(1.23456789, "m")' does not (in the version in develop it
works for both). Perhaps I have made something wrong ...

**Comment by cpascual** [comment]
Hi @teresanunez 

I just tried your script myself and it seems to work fine for both models:

screenshot_20170616_115435

What is exactly what does not fork for you?

PS: The only thing is that I get many deprecation warnings because the models use "//" which is deprecated now (unless you write the authority). This is my fault, since I originally posted a snippet of code using "//" (I've edited it now). But it worked for me both with and without the "//"

PPS: I've also reviewed the code and it seems ok for me

**Comment by teresanunez** [comment]
Hi @cmft, strange ... this is what I see:

taurus_format

Probably is due to some problem in my computer ... a wrong version of something ...

**Comment by cpascual** [comment]
Hi @teresanunez , I think I found the cause. My test was done using a merge of the PR with develop (just as it would be after merging). This brings the fix of  #433  , which affects us in this case. I will now bring the latest develop to this PR and you can try again

**Comment by teresanunez** [comment]
Hi @cpascual, perfect, this was the reason, thanks.

**Pull request merged**
