### PR TITLE
Update instructions for installs on Windows

### PR DESCRIPTION
**Pull request by cpascual**
Make instructions less confusing.
See http://www.tango-controls.org/community/forum/c/general/installation/taurus-on-windows-installation/

### CODE REVIEW

**Comment by bilderbuchi** [comment]
I just spun up a fresh Python 2 environment with Anaconda, and (blindly) followed the platform independent install instructions with pip, on Windows 10. 
Doing `pip install taurus`. Curiously, no dependencies got installed (although I see them in [setup.py](https://github.com/taurus-org/taurus/blob/5ae2469430f0c140218b1daa88ea11c9dd8074e9/setup.py#L58-L67), so when doing `python -c "import taurus; print taurus.Release.version"`, it could not find numpy, of course. I wonder why it did not get installed.
This was with Python 2.7.13, pip 9.0.1, taurus 4.0.3.
A quick `conda install numpy spyder lxml ply pyqt=4` manually installed those dependencies (I did the pyqt installation separately, but it should not matter, although you have to specif that you want pyqt 4).

The output of `check_dependencies` had some weird characters around the OK, ERROR, WARNING bits I noticed:
```
>>> import taurus
>>> taurus.check_dependencies()
Checking required dependencies of taurus.core...
        Checking for Python >=2.6.0... [[0;32mOK[0m] (Found 2.7.13)
Checking OPTIONAL dependencies of taurus.core...
        Checking for PyTango >=7.1.0... [[0;31mERROR[0m] (Not found])
Checking required dependencies of taurus.qt...
        Checking for PyTango >=7.1.0... [[0;31mERROR[0m] (Not found])
        Checking for PyQt >=4.4.0... [[0;32mOK[0m] (Found 4.11.4)
        Checking for PyQwt >=5.2.0... [[0;31mERROR[0m] (Not found])
Checking OPTIONAL dependencies of taurus.qt...
        Checking for Qub >=1.0.0... [[0;33mWARNING[0m] (Not found])
        Checking for spyder >=3.0.0... [[0;32mOK[0m] (Found 3.1.3)
        Checking for qtcontrols >=1.0.0... [[0;33mWARNING[0m] (Not found])
```

**Comment by cpascual** [comment]
>  no dependencies got installed

I also wonder what's going on... I open a separate issue: See #407

> regarding the weird chars: they are TERM colors (which probably are not supported by your terminal on windows10). It is easy to fix that in the `taurushelper._check_dependencies()` method, but I would rather remove the chec_dependencies mechanism from taurus altogether (see #406)

**Comment by cpascual** [comment]
> I just spun up a fresh Python 2 environment with Anaconda

@bilderbuchi, please have a look at #408 ... maybe you can help us with this issue :)

**Comment by cpascual** [comment]
Since this got the possitive review of @teresanunez , I merge it.

**Comment by bilderbuchi** [comment]
Thanks for your input. 
So far, I have become stuck unsuccessfully trying to install pytango (boost not seen although I did `conda install boost`). So since I'm going an unsupported route anyway, i.e. not python(xy), I'll have to let this rest for a while. 
I guess I have been spoiled by using conda/pip w.r.t. automatically obtaining all your dependencies, instead of having to futz around for an hour downloading code/installers from all over the internet. *sigh*

**Pull request merged**
