### PR TITLE
Release jul19

### PR DESCRIPTION
**Pull request by cpascual**
This is a PR **to master** for the official [Jul19 release](https://github.com/taurus-org/taurus/milestone/13). Final tests (automatic and manual) should be done based on it before accepting the merge.

So, **this is a call for help from @taurus-org/integrators and any other person willing to help** to test this branch ASAP in their respective systems. 

For the moment the following tests are planned:

- [x] Debian9, py2qt4, by @teresanunez (#965)
- [x] Debian10, py3qt5 by @mrosanes and @cpascual (#977)
- [x] Win10 py3qt5, by @mrosanes (#959) 
- [x] CentOS 7, py2qt4, by @amilan (#974)
- [x] Debian9, py3qt5 (only partial tests) by @mrosanes and @cpascual (#983)
- ... any other?

(please let us know in the comments of this PR if you plan to do some more manual tests)

Notes:

1. A suggested check-list for the manual tests can be found in [<taurus>/doc/how_to_release.md](https://github.com/taurus-org/taurus/blob/develop/doc/how_to_release.md)
2. the appveyor artifacts  from this PR (use the latest ones) should be used for manual tests (they are preferred to using the git sources, because the git sources may contain files that are not in the artifact).
3. The [taurus-test docker images](https://github.com/cpascual/taurus-test/) may be useful for testing on debian
4. If you do a full check using the check-list, please open an independent issue in order not to spam this PR with long comments (see e.g. #959 )
5. If you want to paste long logs, consider using a [gist](http://gist.github.com/) for that.

### CODE REVIEW

**Comment by cpascual** [comment]
I've updated this release PR to bring fixes for:

- Problem in perspectives Toolbar (reported by @teresanunez in #965)
- Problem with synoptics (reported by @mrosanes in #959 )

**Comment by amilan** [comment]
Hi all,
I can run the manual tests for CentOS7 using the py2qt4 combo.
Cheers,
Antonio.

**Comment by cpascual** [comment]
@amilan 
> I can run the manual tests for CentOS7 using the py2qt4 combo.

That would be nice!

**Comment by amilan** [comment]
Hi, 

Just to let you know that I have done all the manual tests for CentOS7 and py2qt4, and I've found a few issues reported in #980.

Cheers,
Antonio.

**Comment by cpascual** [comment]
I've just closed all the test issues (#959, #965, #977, #974, #983). Some issues have been identified, but none are considered release-critical.

IMHO, the release can go on, so y bumped the version from 4.6.0a --> 4.6.0 and updated the CHANGELOG with today's as the date of the release.

If the other @taurus-org/integrators are fine with it, please approve your pending reviews

**Comment by amilan** [comment]
Hi, 

Although the issues reported are important for MAX IV, I don't consider them as an impediment to continue with the release, and they can be fixed after finishing it.

Cheers.

**Comment by cpascual** [comment]
I updated the release date in the CHANGELOG, and I am merging.

Thanks to all the contributors of this release, and specially to those who worked on the manual tests.

**Pull request merged**
