### PR TITLE
fixing typo and menu changes in users doc

### PR DESCRIPTION
**Pull request by PhilLAL**
That's just minor typo correction, and also some menu titles which seem to have changed.
I did not find a contrib for doc so I hope I've done this with respect to the standard you follow.

I plan to update this PR as I find new typos or menu titles changes.

### CODE REVIEW

**Comment by PhilLAL** [comment]
I am not sure what causes this failure with travis-ci, any idea?

**Comment by LJBD** [comment]
I think it's related to #497...

**Comment by cpascual** [comment]
@PhilLAL 
> I did not find a contrib for doc so I hope I've done this with respect to the standard you follow.

 Yes, a PR is the way for this. When you are done with the changes, remove the "WIP" from the title and do a comment mentioning @taurus-org/integrators so that we can merge it.

Thanks for contributing!

**Comment by PhilLAL** [comment]
You're welcome.

**Comment by PhilLAL** [comment]
I just added one line of clarification about #501

**Comment by PhilLAL** [comment]
Since a new branch would be a more clean method to manage this PR, I remove the WiP to merge this one, and I will create a new one from a new branch later.

**Comment by cpascual** [comment]
> Since a new branch would be a more clean method to manage this PR, I remove the WiP to merge this one, and I will create a new one from a new branch later.

great. merging.

**Pull request merged**
