### PR TITLE
Misplaced figures

### PR DESCRIPTION
**Pull request by PhilLAL**
try to test #545

### CODE REVIEW

**Comment by PhilLAL** [comment]
Precision: the doc has to be built to check figures are well placed in the PDF since I have not been able to build it.

**Comment by cpascual** [comment]
Please merge the latest develop into this branch (solving whatever conflicts) so that we can test it

**Comment by cpascual** [comment]
@PhilLAL : I pushed this to be built in the sandbox.
The result will eventually be available in: https://readthedocs.org/projects/taurus-sandbox/downloads/pdf/phillal-misplaced-figures/

**Comment by cpascual** [comment]
This does not seem to do the trick. 

The solution seems to be to use captions in the figures (so that it does not matter if the figure gets placed too late in the pdf (any help would be appreciated)

See https://github.com/taurus-org/taurus/issues/545#issuecomment-323327916 .

So I am closing this PR and leaving #545 open until someone takes the task of writing captions...

**Pull request closed without merging**
