### PR TITLE
Release jan18

### PR DESCRIPTION
**Pull request by cpascual**
This is a PR **to master** for the official [Jan18 release](https://github.com/taurus-org/taurus/milestone/10). Final tests (automatic and manual) should be done based on it before accepting the merge.

So, **this is a call for help from @taurus-org/integrators and any other person willing to help** to test this branch ASAP in their respective systems. 

We, at ALBA offer to do the manual tests for Debian9 and win7 (unless someone else volunteers for doing them)

Notes:
 - the appveyor artifacts from this PR can be used for manual tests.
 - the [taurus-test docker images](https://github.com/cpascual/taurus-test/) may be useful for testing on debian
 - A suggested check-list for the manual tests can be found in <taurus>/doc/how_to_release.md

### CODE REVIEW

**Comment by cpascual** [comment]
Note: we finally merged the last of the pending PRs for Jan18. 
The tests can be done using the following artifacts:
- [tarball](https://ci.appveyor.com/api/buildjobs/0m5la5936lgx22x3/artifacts/dist%2Ftaurus-4.3.0.tar.gz)
- [msi 32b](https://ci.appveyor.com/api/buildjobs/ovsj80wnr89hu1vm/artifacts/dist%2Ftaurus-4.3.0.win32.msi)
- [msi 64b](https://ci.appveyor.com/api/buildjobs/0m5la5936lgx22x3/artifacts/dist%2Ftaurus-4.3.0.win-amd64.msi)

**Comment by mrosanes** [comment]
Testing on debian9:


### Installation
- [ ] Install Taurus from the tar.gz : `pip install <tarball_artifact_URL>`

### Taurusdemo

- [ ] Test all of the buttons of the taurusdemo. All demos should launch correctly and without raising exceptions
- [ ] For TaurusLabel, check foreground role, the background role, the prefix, the suffix, etc.
- [ ] For TaurusLabel, use a model with fragment (e.g., `sys/tg_test/1/ampli#magnitude`, `eval:Q('1mm')#unit"`)
- [ ] For LCD: Test the foreground roles and the background role
- [ ] For Led: Test the colors, ON color, Off color.

### taurusplot
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [ ] Execute: `taurusplot "eval:Q(rand(333),'mm')" sys/tg_test/1/wave`
- [ ] Check region Zoom in and out with region zoom and go back stacked zoom levels with
- [ ] Check mouse wheel Zoom
- [ ] Test panning (dragging with CTRL pressed)
- [ ] Test inspector mode
- [ ] Test pause mode
- [ ] Move curves between axes by clicking on legend (and test zoom on Y2)
- [ ] Test plot configuration dialog
- [ ] Test changing curve titles
- [ ] Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)
- [ ] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### taurustrend
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [ ] Execute: `taurustrend "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [ ] Execute: `taurustrend -xe "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [ ] Check region Zoom in and out with region zoom and go back stacked zoom levels with
- [ ] Check mouse wheel Zoom
- [ ] Test panning (dragging with CTRL pressed)
- [ ] Test inspector mode
- [ ] Test pause mode
- [ ] Move curves between axes by clicking on legend (and test zoom on Y2)
- [ ] Test plot configuration dialog
- [ ] Test Forced reading mode
- [ ] Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)
- [ ] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### Test taurusimage

- [ ] Execute `taurusimage --demo`
- [ ] try to resize the image and move it using the mouse.

### taurustrend2d

- [ ] Execute: `taurustrend2d --demo --taurus-polling-period 333`
- [ ] Execute: `taurustrend2d -xt --demo --taurus-polling-period 333`  **(known to fail in 4.1.0)**
- [ ] Execute: `taurustrend2d -xe --demo --taurus-polling-period 333`
- [ ] Test auto-scroll and auto-scale tools
- [ ] Test Save & restore config (change axes range, zoom, tool status colormap etc & check that everything is restored)

### Tauruscurve & taurustrend1d
(unused and to be deprecated, you may test but **do not worry too much if they fail**)

- [ ] Execute: `tauruscurve --demo` and `taurustrend1d "eval:Q(rand(),'mm')"`
- [ ] Change size
- [ ] Move curve with mouse
- [ ] Resize curve with mouse
- [ ] Test some option of the menu with mouse.

### taurusdesigner
- [ ] Check that taurusdesigner is correctly opened and taurus widgets are present in the catalog
- [ ] Create an empty widget and drag various taurus widgets to it (they should be correctly dropped)

### taurusdevicepanel
- [ ] Execute: `taurusdevicepanel sys/tg_test/1`
- [ ] Check that it opens correctly and that the attrs and commands are populated
- [ ] Execute SwitchStates command (see that the state label changes to FAULT and its color to red)
      and then execute the Init command and the label returns to RUNNING (green)

### tauruspanel
- [ ] Execute: `tauruspanel`
- [ ] Navigate in the tree and select the TangoTest device (the attr an command panels should be populated)

### taurusform
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [ ] Launch `taurusform sys/tg_test/1/short_scalar`
- [ ] Test to drag and drop of this attribute onto the same form many times (4 times)
      (If it crashes, you are seeing bug #96)
- [ ] Open "Modify Contents" and add sys/tg_test/1 and all of its attributes. They should all show ok
- [ ] Test the compact mode  (switch to compact, noncompact; edit when in compact mode, ...) for a single
      value (from the context menu of a value label)
- [ ] Test compact mode for all values (from the context menu of the whole form)
- [ ] Test changing labels
- [ ] Test re-order of values with "Modify contents"
- [ ] Test the different "show" buttons (tables, images, spectra)
- [ ] Change the write widget of double_scalar by a TaurusWheelEdit
- [ ] Change other read and write widgets
- [ ] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### taurusgui
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [ ] Launch `taurusgui example01`
- [ ] Test (un)lock view
- [ ] Create a new panel (a TaurusForm) and drag and drop several models from other forms
- [ ] Move panels around (with view unlocked!) and hide ("close") and re-show them
- [ ] Test saving and restoring perspectives
- [ ] Test drag&drop from a form to a trend
- [ ] Test drag&drop from a form to a trend
- [ ] Test clicking on "example01 synoptic" elements and check that the panels raised
- [ ] Test that selecting a panel changes the selection on "example01 synoptic"
- [ ] Test the actions in the menus
- [ ] Create a new TaurusGui (call it `foogui`) with `taurusgui --new-gui` (follow the wizard)
- [ ] Install `foogui` with pip (using a virtualenv may be a good idea)
- [ ] launch `foogui` using the script that has been installed
- [ ] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)


### taurusconfigbrowser
- [ ] Open an ini file with taurusconfigbrowser and check that it is loaded correctly.

### taurusiconcatalog
- [ ] Launch `taurusiconcatalog`. Several tabs with an array of icons [should be displayed](http://taurus-scada.org/en/latest/devel/icon_guide.html#taurus-icon-catalog)
- [ ] Check that tooltips give info on each icon
- [ ] Click on some icons and check that they give a bigger view of the icon and more info.

**Comment by mrosanes** [comment]
Testing on Win7:


### Installation
- [x] Install Taurus 32bits from the msi

### Taurusdemo

- [] Test all of the buttons of the taurusdemo. All demos should launch correctly and without raising exceptions
Failure in Message panel exceptions 2,3 and 4: https://gist.github.com/mrosanes/ce5cbc0e6a1c7894a234af94b1916ab6

- [] For TaurusLabel, check foreground role, the background role, the prefix, the suffix, etc.
Failure: value as background role
https://gist.github.com/mrosanes/900c850be3445231a4b715d8061e102b

- [] For TaurusLabel, use a model with fragment (e.g., `sys/tg_test/1/ampli#magnitude`, `eval:Q('1mm')#unit"`)
- [] For LCD: Test the foreground roles and the background role
- [] For Led: Test the colors, ON color, Off color.

### taurusplot
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [] Execute: `taurusplot "eval:Q(rand(333),'mm')" sys/tg_test/1/wave`
- [] Check region Zoom in and out with region zoom and go back stacked zoom levels with
- [] Check mouse wheel Zoom
- [] Test panning (dragging with CTRL pressed)
- [] Test inspector mode
- [] Test pause mode
- [] Move curves between axes by clicking on legend (and test zoom on Y2)
- [] Test plot configuration dialog
- [] Test changing curve titles
- [] Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)
- [] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### taurustrend
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [] Execute: `taurustrend "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [] Execute: `taurustrend -xe "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [] Check region Zoom in and out with region zoom and go back stacked zoom levels with
- [] Check mouse wheel Zoom
- [] Test panning (dragging with CTRL pressed)
- [] Test inspector mode
- [] Test pause mode
- [] Move curves between axes by clicking on legend (and test zoom on Y2)
- [] Test plot configuration dialog
- [] Test Forced reading mode
- [] Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)
- [] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### Test taurusimage

- [] Execute `taurusimage --demo`
- [] try to resize the image and move it using the mouse.

### taurustrend2d

- [] Execute: `taurustrend2d --demo --taurus-polling-period 333`
- [] Execute: `taurustrend2d -xt --demo --taurus-polling-period 333`  **(known to fail in 4.1.0 and 4.3.0)**
https://gist.github.com/mrosanes/189327898c83f92e9663b32cc96fc499
- [] Execute: `taurustrend2d -xe --demo --taurus-polling-period 333`
- [] Test auto-scroll and auto-scale tools
- [] Test Save & restore config (change axes range, zoom, tool status colormap etc & check that everything is restored)

### Tauruscurve & taurustrend1d
(unused and to be deprecated, you may test but **do not worry too much if they fail**)

- [] FAIL: Execute: `tauruscurve --demo`
```tauruscurve --demo``` fails, and ```tauruscurve <model>``` fails as well
https://gist.github.com/mrosanes/1ebf0be6fb52280bd0dd4b9f7d35355c
- [] FAIL: Execute `taurustrend1d "eval:Q(rand(),'mm')"`
taurustrend1d fails
- [] Change size
- [] Move curve with mouse
- [] Resize curve with mouse
- [] Test some option of the menu with mouse.

### taurusdesigner
- [] Check that taurusdesigner is correctly opened and taurus widgets are present in the catalog
- [] Create an empty widget and drag various taurus widgets to it (they should be correctly dropped)

### taurusdevicepanel
- [] Execute: `taurusdevicepanel sys/tg_test/1`
It works but it takes many seconds to load.

- [] Check that it opens correctly and that the attrs and commands are populated
- [] Execute SwitchStates command (see that the state label changes to FAULT and its color to red)
      and then execute the Init command and the label returns to RUNNING (blue using Tango)

### tauruspanel
- [] Execute: `tauruspanel`
- [] Navigate in the tree and select the TangoTest device (the attr an command panels should be populated)
It works, but it takes a lot of time: around 10 seconds to populate the panel of sys/tg_test/1

### taurusform
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [] Launch `taurusform sys/tg_test/1/short_scalar`
- [] Test to drag and drop of this attribute onto the same form many times (4 times)
      (If it crashes, you are seeing bug #96)
- [] Open "Modify Contents" and add sys/tg_test/1 and all of its attributes. They should all show ok
- [] Test the compact mode  (switch to compact, noncompact; edit when in compact mode, ...) for a single
      value (from the context menu of a value label)
- [] Test compact mode for all values (from the context menu of the whole form)
- [] Test changing labels
- [] Test re-order of values with "Modify contents"
- [] Test the different "show" buttons (tables, images, spectra)
- [] Change the write widget of double_scalar by a TaurusWheelEdit
- [] Change other read and write widgets
- [] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### taurusgui
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [] Launch `taurusgui example01`
- [] Test (un)lock view
Failure at the beginning: when opening example01 for the first time after installing taurus, the view is locked but the panels can be put at the interior of the main Window and they can be moved freely: I think this is a wrong behavior. Once the unlock is done, and we lock it again, the lock is applied correctly.
- [] Create a new panel (a TaurusForm) and drag and drop several models from other forms
- [] Move panels around (with view unlocked!) and hide ("close") and re-show them
- [] Test saving and restoring perspectives
- [] Test drag&drop from a form to a trend
- [] Test drag&drop from a form to a trend
- [] Test clicking on "example01 synoptic" elements and check that the panels raised
- [] Test that selecting a panel changes the selection on "example01 synoptic"
- [] Test the actions in the menus
- [] Create a new TaurusGui (call it `foogui`) with `taurusgui --new-gui` (follow the wizard)
- [] Install `foogui` with pip (using a virtualenv may be a good idea)
- [] launch `foogui` using the script that has been installed
- [] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)


### taurusconfigbrowser
- [] Open an ini file with taurusconfigbrowser and check that it is loaded correctly.
NOTE: taurusgui --new-gui stores its configuration in folder 'TAURUS'; however, taurusgui example01 stores it in another folder named 'Taurus'. This could be homogenized. 

### taurusiconcatalog
- [] Launch `taurusiconcatalog`. Several tabs with an array of icons [should be displayed](http://taurus-scada.org/en/latest/devel/icon_guide.html#taurus-icon-catalog)
- [] Check that tooltips give info on each icon
- [] Click on some icons and check that they give a bigger view of the icon and more info.

**Comment by mrosanes** [comment]
All bugs detected on windows for Taurus4.3, where also present in Taurus4.1, excepting:
1- The 'value' as background role for label (tests of taurusdemo)
2- Spinbox arrows

This bugs does not seem release critical

**Comment by mrosanes** [comment]
After having modified the installation of the Taurus dependencies in the Windows7 Vagrant file, the programs are not crashing anymore when closing, but the Windows console is not returning the prompt. However the behavior without crashing is better.

Dependencies installed with pip:
Cython==0.27.3
numpy==1.14.1
qtpy==1.3.1
Pillow==5.0.0
PythonQwt==0.5.5
guidata==1.7.6
 scipy==1.0.0 (without dependencies: --no-deps)
spyder==3.2.7 (without dependencies)
guiqwt==3.0.3 (without dependencies)

**Comment by cpascual** [comment]
>All bugs detected on windows for Taurus4.3, where also present in Taurus4.1, excepting:
>1- The 'value' as background role for label (tests of taurusdemo)

This is not really a bug. The "value" for the background only makes sense with a "state" attribute

>2- Spinbox arrows

This should be fixed now in the release-Jan18 branch (see #707)

**Comment by cpascual** [comment]
The release is finally ready ("only" 29 days later...)  

Thanks to all contributors, bug reporters and testers!

Merging to master

**Pull request merged**
