### PR TITLE
Do not keep a device alive just because an attribute is polled

### LINKED ISSUE #999: TaurusAttributeListComboBox API_EventTimeout when setting unavailable <MacroServer>/DoorList
You can use the following snippet to reproduce it.

Note that the `MacroServer/demo1/1` must be unavailable and the `MacroServer/py3/1` must be available.

```python
from taurus.external.qt import Qt
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.input import TaurusAttrListComboBox

def setModel():
    model = "MacroServer/py3/1/doorList"
    w.setModel(model)

a = TaurusApplication(cmd_line_parser=None)
w = TaurusAttrListComboBox()
model = "MacroServer/demo1/1/doorList"
w.setModel(model)
w.show()
timer = Qt.QTimer()
timer.timeout.connect(setModel)
timer.start(1000)
a.exec_()
```

Later, after approx 10 s we get:

```
Dummy-161      INFO     2019-09-09 19:31:41,862 pc255.cells.es:10000.MS_py3_1.doorList: Activating polling. Reason: API_EventTimeout
TimerLoop 1    ERROR    2019-09-09 19:31:41,864 TaurusPollingTimer[3000]: poll_reply error
Dummy-161      INFO     2019-09-09 19:31:41,868 pc255.cells.es:10000.MS_py3_1.Elements: Activating polling. Reason: API_EventTimeout
TimerLoop 1    ERROR    2019-09-09 19:31:41,872 TaurusPollingTimer[3000]: poll_reply error
Dummy-161      INFO     2019-09-09 19:31:41,893 pc255.cells.es:10000.MS_py3_1.Environment: Activating polling. Reason: API_EventTimeout
Dummy-161      INFO     2019-09-09 19:31:51,901 pc255.cells.es:10000.MS_py3_1.doorList: Activating polling. Reason: API_EventTimeout
Dummy-161      INFO     2019-09-09 19:31:51,905 pc255.cells.es:10000.MS_py3_1.Elements: Activating polling. Reason: API_EventTimeout
TimerLoop 1    ERROR    2019-09-09 19:31:51,908 TaurusPollingTimer[3000]: poll_reply error
Dummy-161      INFO     2019-09-09 19:31:51,934 pc255.cells.es:10000.MS_py3_1.Environment: Activating polling. Reason: API_EventTimeout
Dummy-161      INFO     2019-09-09 19:32:01,942 pc255.cells.es:10000.MS_py3_1.doorList: Activating polling. Reason: API_EventTimeout
Dummy-161      INFO     2019-09-09 19:32:01,945 pc255.cells.es:10000.MS_py3_1.Elements: Activating polling. Reason: API_EventTimeout
TimerLoop 1    ERROR    2019-09-09 19:32:01,948 TaurusPollingTimer[3000]: poll_reply error
Dummy-161      INFO     2019-09-09 19:32:01,972 pc255.cells.es:10000.MS_py3_1.Environment: Activating polling. Reason: API_EventTimeout
Dummy-161      INFO     2019-09-09 19:32:11,979 pc255.cells.es:10000.MS_py3_1.doorList: Activating polling. Reason: API_EventTimeout
Dummy-161      INFO     2019-09-09 19:32:11,983 pc255.cells.es:10000.MS_py3_1.Elements: Activating polling. Reason: API_EventTimeout
Dummy-161      INFO     2019-09-09 19:32:12,085 pc255.cells.es:10000.MS_py3_1.Environment: Activating polling. Reason: API_EventTimeout
```

I have my TANGO_HOST set to FQDN Tango DB.

### PR DESCRIPTION
**Pull request by cmft**
The TaurusPollingTimer keeps device strong references
for creating the  weakref dictionary of polled attributes.
The removeAttribute does not cleanup the structures and
many of TaurusPollingTimer methods are not thread-safe.

Fix removeAttribute implementation to delete unreferenced
elements.
Protect the methods using the lock or making copy of the
iterated containers.

Fix #999

### CODE REVIEW

**Comment by cpascual** [comment]
Hi @cmft: can you please add a unit test to this PR?

**Comment by cmft** [comment]
> Hi @cmft: can you please add a unit test to this PR?

Done

**Comment by cmft** [comment]
I found troubles with this PR: there are many  `TaurusPollingTimer[3000]: poll_reply error KeyError('Status',)` with some GUIs. For example  running `taurus --log-level Debug device  sys/database/2`

**Comment by cmft** [comment]
The bug seems to be not fixed in python3, moreover there is a related issue  when it is used the `state` attr.

```
def test_polling_bug999():
    polling_period = .1  # seconds
    a = taurus.Attribute('sys/tg_test/1/state')
    f = a.factory()
    a.activatePolling(polling_period * 10000, force=True)
    assert len(list(f.tango_attrs.keys())) == 1
    assert len(list(f.tango_devs.keys())) == 1
    a = None
    time.sleep(polling_period)
    print(list(f.tango_attrs.keys()))
    assert len(list(f.tango_attrs.keys())) == 0
    assert len(list(f.tango_devs.keys())) == 0

```

**Comment by cpascual** [comment]
I am concerned about some segfaults that we are [seeing in the tests](https://travis-ci.org/taurus-org/taurus/jobs/623565096#L472) . The traces [seem to blame (py?)tango's  event subscription](https://travis-ci.org/taurus-org/taurus/jobs/623565096#L523) (tox reports using pytango 9.3.1 from conda).

The segfault is not happening all the time, but it is worrying enough.

Hint: If we know of some some specific version of (py)tango (or other related lib) that is not affected, maybe we could try to pin the safe version in the `tox.ini`

**Pull request merged**
