### PR TITLE
Fix false successes in travis unittests

### PR DESCRIPTION
**Pull request by cpascual**
This PR is for checking if Travis is actually reporting failures or not.

Concerns are raised in https://github.com/taurus-org/taurus/pull/681#issuecomment-365573163

### CODE REVIEW

**Comment by cpascual** [comment]
Confirmed. Travis is [now silently ignoring failing tests](https://travis-ci.org/taurus-org/taurus/builds/341514620):

image

**Comment by cpascual** [comment]
The problem with the false successes seems to be caused by the use of travis_wait, since its removal now leads to travis reporting [various failures/errors](https://github.com/taurus-org/taurus/pull/683/commits/b3be7a66f99474243024df6540ab07ed55ee4c19) in the unittests which were previously silently ignored:

```
----------------------------------------------------------------------
Ran 539 tests in 92.191s
FAILED (failures=1, errors=21, skipped=8)
```

Note: the failures now reported by Travis are not reproduced locally. A local run of the unittests shows only 2 failing tests (the one we [intentionally introduced](https://github.com/taurus-org/taurus/pull/683/commits/b3be7a66f99474243024df6540ab07ed55ee4c19) and one related to writing epics attributes (which may be related to #588)

```
$ TAURUS_STARTER_WAIT=5 taurustestsuite -e 'taurus\.core\.util\.test\.test_timer'

(...)
======================================================================
ERROR: test_write_read_attr (taurus.core.epics.test.test_epicsattribute.AttributeTestCase)
Testing write_read_attr(attrname='ca:test:a', expected={'writable': True, 'range': [<Quantity(-10, 'meter')>, <Quantity(10, 'meter')>], 'warnings': [None, None], 'alarms': [None, None], 'rvalue': <Quantity(1, 'meter')>, 'type': 1, 'data_format': 0}, expected_attrv={'wvalue': <Quantity(1, 'meter')>, 'rvalue': <Quantity(1, 'meter')>, 'quality': <AttrQuality.ATTR_VALID: 0>, 'error': None}, setvalue=<Quantity(1000, 'millimeter')>)
----------------------------------------------------------------------
Traceback (most recent call last):
(...)
AttributeError: 'NoneType' object has no attribute 'items'

======================================================================
FAIL: test_text_5 (taurus.qt.qtgui.display.test.test_tauruslabel.TaurusLabelTest2)
Testing text(expected='SOMETHING CLEARLY WRONG', model='tango:TangoSchemeTest/unittest/temp-1/double_scalar#state')
----------------------------------------------------------------------
(...)
AssertionError: wrong text for "tango:TangoSchemeTest/unittest/temp-1/double_scalar#state":
 expected: SOMETHING CLEARLY WRONG
 got: Ready

----------------------------------------------------------------------
Ran 625 tests in 183.232s

FAILED (failures=1, errors=1, skipped=5)

```

**Comment by cpascual** [comment]
Conclusion: 
- travis_wait was hiding unit test aborts and silently ignoring them as if everything was ok
- Once travis_wait was removed, we found that some tests related to Tango access were failing only in travis (not locally). A workaround for this inspired by https://github.com/sardana-org/sardana/pull/669 has been put in place. 

Now unittests in travis are functional again

**Comment by reszelaz** [comment]
Just for the record, the investigation about this error is already in progress in https://github.com/sardana-org/sardana/pull/670. At some point we should come back to it..

**Pull request merged**
