### PR TITLE
Fix-365: Refactor TangoAttribute push_event

### LINKED ISSUE #261: Random failures in testsuite (workaround exists, but proper fix is pending)
The testsuite is not robust.
Running the taurus testsuite sometimes results in "spurious" failures. This tends to affect more the Travis builds (although it also happens -less frequently- when using the taurus-test docker locally ) and , with even less frequency when running the tests directly in my desktop.

In the case of travis builds, the spurious failures occur almost on every build of the develop branch, which makes it very difficult for CI.

The failures are quite random, although they seem always related with some kind of race condition when access to tango is involved. See, e.g.:

-  https://travis-ci.org/cpascual/taurus/builds/154108424
-  https://travis-ci.org/cpascual/taurus/builds/154668211
-  ...

The following changes seem to alleviate the problem for the taurus.qt tests:

```
diff --git a/lib/taurus/qt/qtgui/base/test/test_taurusbase.py b/lib/taurus/qt/qtgui/base/test/test_taurusbase.py
index 3c6c915..66c9521 100644
--- a/lib/taurus/qt/qtgui/base/test/test_taurusbase.py
+++ b/lib/taurus/qt/qtgui/base/test/test_taurusbase.py
@@ -94,6 +94,8 @@ class GetDisplayValueTestCase(TangoSchemeTestLauncher, BaseWidgetTestCase,
     def getDisplayValue(self, model=None, expected=None):
         '''Check if setModel works when using parent model'''
         self._widget.setModel(model)
+        import time
+        time.sleep(1)
         got = self._widget.getDisplayValue()
         msg = ('getDisplayValue for "%s" should be %r (got %r)' %
                (model, expected, got))
diff --git a/lib/taurus/qt/qtgui/test/base.py b/lib/taurus/qt/qtgui/test/base.py
index 2fff74c..9e66221 100644
--- a/lib/taurus/qt/qtgui/test/base.py
+++ b/lib/taurus/qt/qtgui/test/base.py
@@ -69,6 +69,8 @@ class BaseWidgetTestCase(object):

         if self._klass is not None:
             self._widget = self._klass(*self.initargs, **self.initkwargs)
+        import time
+        time.sleep(1)

     def assertMaxDeprecations(self, maximum, msg=None):
         """Assertion method that checks that the number of deprecations issued
```

Reported by: cpascual ( http://sf.net/u/cpascual )

### LINKED ISSUE #365: TangoAttribute may not properly handle errors in config events
Taurus4 may have introduced a regression related to the merge of TaurusAttribute and TaurusConfiguration. The new TangoAttribute.push_event method now handles all events (Change, Config...) but its logic may be faulty in some specific situations (e.g., when a configuration-related error event is received before the TangoAttribute has been initialized, which [with Tango9 may be more likely](http://www.tango-controls.org/community/forum/c/general/development/attr_conf_event-difference-between-tango-8-and-tango-9/))

In this situation, the TangoAttribute may end up flagged as subscribed but not having actually subscribed, preventing to become properly subscribed when a non-error event comes later on.
It also may incorrectly deactivate the polling mechanism.

### PR DESCRIPTION
**Pull request by cpascual**
Fix #365. (and also fix #261 as a side-effect)

Taurus4 introduced a regression related to the merge of TaurusAttribute
and TaurusConfiguration. The TangoAttribute.push_event method handles
all events but it doesn't do it properly for configuration-related
error events received before the TangoAttribute has been initialized.

In this situation, the TangoAttribute ends up flagged as subscribed
but the subscription was not actually done, preventing to become
properly subscribed when a non-error event comes later on.
It also may incorrectly deactivate the polling mechanism.

Refactor the push_event code to clean it and correctly handle conf
errors.

Notes:
- As part of the review and integration of this change, we needed to deal 
with the spurious failures in travis (#261 ). This PR also makes the testsuite 
more robust (not infalible, though). It is enough IMHO to Fix #261.

- this seems to solve the issue with the Sardana server reported in:
https://sourceforge.net/p/sardana/mailman/message/35591825/
(we tried with this change, with sardana from develop and the tango9 stack 
from debian9 repos... and we successfully ran sar_demo using a single 
Sardana instance)

### CODE REVIEW

**Comment by cpascual** [comment]
Note that travis shows [many failures](https://travis-ci.org/taurus-org/taurus/builds/191611239) in tests... they need to be investigated before accepting this PR

**Comment by cpascual** [comment]
Investigating the travis errors, with @sagiss ... It seems like they are (again) linked to #261, i.e., they are spurious failures, hard to reproduce outside travis.

After forcing a re-run, we went from 8 errors to only 1:

~~~~
======================================================================

/usr/local/lib/python2.7/dist-packages/taurus-4.0.3a0-py2.7.egg/taurus/core/resource/test/res/attr_resources_file.py

FAIL: test_texts (taurus.qt.qtgui.panel.test.test_taurusvalue.TaurusValueTest)

Testing texts(expected=('double_scalar', '1.23', '0.0 mm', 'mm'), model='tango:TangoSchemeTest/unittest/temp-1/double_scalar')

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/taurus-4.0.3a0-py2.7.egg/taurus/test/base.py", line 113, in newTest

    return helper(**helper_kwargs)

  File "/usr/local/lib/python2.7/dist-packages/taurus-4.0.3a0-py2.7.egg/taurus/qt/qtgui/panel/test/test_taurusvalue.py", line 77, in texts

    self.assertEqual(got, expected, msg)

AssertionError: wrong text for "tango:TangoSchemeTest/unittest/temp-1/double_scalar":

 expected: ('double_scalar', '1.23', '0.0 mm', 'mm')

 got: ('double_scalar', '-----', 'None', '')

----------------------------------------------------------------------

Ran 560 tests in 78.112s

FAILED (failures=1, skipped=11)
~~~~


I am re-running it again in the hope that we get a clean build in travis to confirm that this is all #261 - related

**Comment by sagiss** [comment]
On docker cpascual/taurus-test (launching the taurustestsuite outside travis), I managed to reproduce the failures that were appearing before on Travis.

<pre>

root@taurus-test:/# 
...
======================================================================
FAIL: test_write_read_attr_13 (taurus.core.tango.test.test_tangoattribute.AttributeTestCase)
Testing write_read_attr(attrname='short_scalar', expected={'warnings': [<Quantity(-369, 'millimeter')>, <Quantity(369, 'millimeter')>], 'wvalue': <Quantity(1000, 'millimeter')>, 'rvalue': <Quantity(1000, 'millimeter')>, 'data_format': 0, 'label': 'short_scalar', 'writable': True, 'range': [<Quantity(-1230, 'millimeter')>, <Quantity(1230, 'millimeter')>], 'alarms': [<Quantity(-615, 'millimeter')>, <Quantity(615, 'millimeter')>], 'type': 0}, expected_attrv={'w_value': 1000, 'quality': <AttrQuality.ATTR_ALARM: 2>, 'value': 1000}, setvalue=<Quantity(1, 'meter')>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/taurus/lib/taurus/test/base.py", line 113, in newTest
    return helper(**helper_kwargs)
  File "/home/taurus/lib/taurus/core/tango/test/test_tangoattribute.py", line 771, in write_read_attr
    self.assertTrue(isinstance(read_value, TangoAttrValue), msg)
AssertionError: read() for "short_scalar" did not return a TangoAttrValue (got a NoneType)

======================================================================
FAIL: test_write_read_attr_16 (taurus.core.tango.test.test_tangoattribute.AttributeTestCase)
Testing write_read_attr(attrname='double_scalar', expected={'wvalue': <Quantity(3, 'millimeter')>, 'rvalue': <Quantity(3, 'millimeter')>, 'type': 1}, expected_attrv={'w_value': 3, 'quality': <AttrQuality.ATTR_VALID: 0>, 'value': 3}, setvalue=<Quantity(3, 'millimeter')>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/taurus/lib/taurus/test/base.py", line 113, in newTest
    return helper(**helper_kwargs)
  File "/home/taurus/lib/taurus/core/tango/test/test_tangoattribute.py", line 771, in write_read_attr
    self.assertTrue(isinstance(read_value, TangoAttrValue), msg)
AssertionError: read() for "double_scalar" did not return a TangoAttrValue (got a NoneType)

======================================================================
FAIL: test_write_read_attr_17 (taurus.core.tango.test.test_tangoattribute.AttributeTestCase)
Testing write_read_attr(attrname='double_scalar', expected={'wvalue': <Quantity(4, 'millimeter')>, 'rvalue': <Quantity(4, 'millimeter')>}, expected_attrv={'wvalue': <Quantity(0.004, 'meter')>, 'rvalue': <Quantity(4, 'millimeter')>, 'quality': <AttrQuality.ATTR_WARNING: 4>}, setvalue=<Quantity(0.004, 'meter')>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/taurus/lib/taurus/test/base.py", line 113, in newTest
    return helper(**helper_kwargs)
  File "/home/taurus/lib/taurus/core/tango/test/test_tangoattribute.py", line 771, in write_read_attr
    self.assertTrue(isinstance(read_value, TangoAttrValue), msg)
AssertionError: read() for "double_scalar" did not return a TangoAttrValue (got a NoneType)

======================================================================
FAIL: test_write_read_attr_18 (taurus.core.tango.test.test_tangoattribute.AttributeTestCase)
Testing write_read_attr(attrname='double_scalar', expected={'alarms': [<Quantity(-6.15, 'millimeter')>, <Quantity(6.15, 'millimeter')>], 'range': [<Quantity(-12.3, 'millimeter')>, <Quantity(12.3, 'millimeter')>], 'name': 'double_scalar', 'warnings': [<Quantity(-3.69, 'millimeter')>, <Quantity(3.69, 'millimeter')>], 'wvalue': <Quantity(10, 'millimeter')>, 'rvalue': <Quantity(0.01, 'meter')>, 'type': 1}, expected_attrv={'wvalue': <Quantity(10, 'millimeter')>, 'w_value': 10, 'rvalue': <Quantity(0.01, 'meter')>, 'quality': <AttrQuality.ATTR_ALARM: 2>, 'value': 10}, setvalue=<Quantity(0.01, 'meter')>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/taurus/lib/taurus/test/base.py", line 113, in newTest
    return helper(**helper_kwargs)
  File "/home/taurus/lib/taurus/core/tango/test/test_tangoattribute.py", line 771, in write_read_attr
    self.assertTrue(isinstance(read_value, TangoAttrValue), msg)
AssertionError: read() for "double_scalar" did not return a TangoAttrValue (got a NoneType)

======================================================================
FAIL: test_write_read_attr_19 (taurus.core.tango.test.test_tangoattribute.AttributeTestCase)
Testing write_read_attr(attrname='float_scalar', expected={'wvalue': <Quantity(3, 'millimeter')>, 'rvalue': <Quantity(3, 'millimeter')>, 'type': 1}, expected_attrv={'w_value': 3, 'quality': <AttrQuality.ATTR_VALID: 0>, 'value': 3}, setvalue=<Quantity(3, 'millimeter')>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/taurus/lib/taurus/test/base.py", line 113, in newTest
    return helper(**helper_kwargs)
  File "/home/taurus/lib/taurus/core/tango/test/test_tangoattribute.py", line 771, in write_read_attr
    self.assertTrue(isinstance(read_value, TangoAttrValue), msg)
AssertionError: read() for "float_scalar" did not return a TangoAttrValue (got a NoneType)

======================================================================
FAIL: test_write_read_attr_20 (taurus.core.tango.test.test_tangoattribute.AttributeTestCase)
Testing write_read_attr(attrname='float_scalar', expected={'wvalue': <Quantity(4, 'millimeter')>, 'rvalue': <Quantity(4, 'millimeter')>}, expected_attrv=': <Quantity(0.004, 'meter')>, 'rvalue': <Quantity(4, 'millimeter')>, 'quality': <AttrQuality.ATTR_WARNING: 4>}, setvalue=<Quantity(0.004, 'meter')>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/taurus/lib/taurus/test/base.py", line 113, in newTest
    return helper(**helper_kwargs)
  File "/home/taurus/lib/taurus/core/tango/test/test_tangoattribute.py", line 771, in write_read_attr
    self.assertTrue(isinstance(read_value, TangoAttrValue), msg)
AssertionError: read() for "float_scalar" did not return a TangoAttrValue (got a NoneType)

======================================================================
FAIL: test_write_read_attr_21 (taurus.core.tango.test.test_tangoattribute.AttributeTestCase)
Testing write_read_attr(attrname='float_scalar', expected={'alarms': [<Quantity(-6.15, 'millimeter')>, <Quantity(6.15, 'millimeter')>], 'range': [<Quanti, 'millimeter')>, <Quantity(12.3, 'millimeter')>], 'name': 'float_scalar', 'warnings': [<Quantity(-3.69, 'millimeter')>, <Quantity(3.69, 'millimeter')>],': <Quantity(10, 'millimeter')>, 'rvalue': <Quantity(0.01, 'meter')>, 'type': 1}, expected_attrv={'wvalue': <Quantity(10, 'millimeter')>, 'w_value': 10, : <Quantity(0.01, 'meter')>, 'quality': <AttrQuality.ATTR_ALARM: 2>, 'value': 10}, setvalue=<Quantity(0.01, 'meter')>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/taurus/lib/taurus/test/base.py", line 113, in newTest
    return helper(**helper_kwargs)
  File "/home/taurus/lib/taurus/core/tango/test/test_tangoattribute.py", line 771, in write_read_attr
    self.assertTrue(isinstance(read_value, TangoAttrValue), msg)
AssertionError: read() for "float_scalar" did not return a TangoAttrValue (got a NoneType)

======================================================================
FAIL: test_write_read_attr_24 (taurus.core.tango.test.test_tangoattribute.AttributeTestCase)
Testing write_read_attr(attrname='boolean_scalar', expected={'writable': True, 'alarms': [None, None], 'range': [None, None], 'warnings': [None, None], ' False, 'rvalue': False, 'type': 3}, expected_attrv={'wvalue': False, 'w_value': False, 'rvalue': False, 'quality': <AttrQuality.ATTR_VALID: 0>, 'value': setvalue=False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/taurus/lib/taurus/test/base.py", line 113, in newTest
    return helper(**helper_kwargs)
  File "/home/taurus/lib/taurus/core/tango/test/test_tangoattribute.py", line 771, in write_read_attr
    self.assertTrue(isinstance(read_value, TangoAttrValue), msg)
AssertionError: read() for "boolean_scalar" did not return a TangoAttrValue (got a NoneType)

----------------------------------------------------------------------
Ran 560 tests in 79.258s

FAILED (failures=8, skipped=11)


</pre>

**Comment by cpascual** [comment]
I included several commits (cherry-picked and reworked from https://github.com/cmft/taurus/pull/3) that should boost the robustness of the testsuite (they fix/work-around causes  of #261).

**Comment by cpascual** [comment]
@cmft and me reviewed (and pair-programmed) this, so I am accepting the PR

**Pull request merged**
