### PR TITLE
Refactor the test CI: use tox, pytest and tango-cs-docker

### PR DESCRIPTION
**Pull request by cpascual**
This PR proposes a complete refactoring of our CI in travis.

Improvements:
1. Based in [tox](https://tox.readthedocs.io) + [tox-conda](https://github.com/tox-dev/tox-conda) (tests can be reproduced locally in a similar way as they are executed by travis). 
2. The tango support in travis is provided by [tango-cs-docker](https://github.com/tango-controls/tango-cs-docker) *running as an independent service*. We do not use or need the taurus-test images now.
3. Facilitates adding new tests and test environments: this PR already adds tests for various interesting combinations of versions of python (2.7, 3.5, 3.6, 3.7), and of Qt bindings (PyQt4, PyQt5 and Pyside2), as well as flake8 tests and doc builds.
4. Tests are run with [PyTest](https://pytest.org/) instead of unittest (the tests are not changed for now, just run with PyTest even if they are implemented with unittest). In practice, we see that the travis builds seem more robust now(maybe #851 is fixed by this?). It also opens the door to using many interesting features of PyTest (fixtures, parameterizations, pytest-qt,...)
5. We can use tox to deploy local environments for test and development:
   ```
   tox --devenv -e py37-qt5 taurusenv
   ```
6. A flake8 test is implemented, but for now it is allowed to fail (I intend to submit another PR fixing all flake8 issues in taurus) 
 
Notes for integrators:
- The results can be seen in https://travis-ci.org/taurus-org/taurus/builds/578400811
- The docs generated by travis are in https://taurus-org.github.io/taurus-doc/v-pytest
- One can also run all the tests locally (on a system with conda available) by running `tox` (this takes long, so one can list the environments with `tox -l` and run only a selectionwith `tox -e`)

### CODE REVIEW

**Comment by mrosanes** [comment]
Great work!

**Comment by cpascual** [comment]
Hi @taurus-org/integrators , can someone review an integrate this ? 
It would be nice to have it integrated to facilitate the cleaning flake8 issues

**Comment by teresanunez** [comment]
Hi carlos, I have had a look and I agree with the changes you mention and the outputs are
 fine to me. But I can not tested. if this is enough I could integrate it, but perhaps somebody else
 wants to test it first. Many thanks for the work.

**Comment by cpascual** [comment]
Hi @teresanunez, thanks for reviewing.

In principle the tests are done already by travis, so it is more about agreeing in the objective and implementation.

In any case, running the tests locally, should just be a matter of:
- having (mini)conda installed
- creating a conda env with `tox-conda` in it: 
```
conda create -n toxconda tox-conda
```
- From the toxconda environment, run all the tox targets of taurus (or select some with -e):

```
conda activate toxconda
cd <taurusdir>  # taurusdir is a checkout of this PR
export TOX_TESTENV_PASSENV=TANGO_HOST  # you can skip this if you define the tango host in a /etc/tangorc file
tox   # this will run all the targets. use -e to select only a few
```

**Comment by cpascual** [comment]
The last changes from @cmft are a good addition (they help running tox locally)

**Comment by reszelaz** [comment]
Both @cmft and myself had run the test locally and no issues were observed. I do not have time to review the changes carefully but since there is already agreemend from @teresanunez I simply merge it now.

**Pull request merged**
