### PR TITLE
Allow disable some TaurusGui parts.

### PR DESCRIPTION
**Pull request by droldan**
The purpose of this PR is to lighten TaurusGui, allowing disabling programmatically parts of the TaurusGui not needed.

#### The bar on the right:
_enableJorgsBar(True)_: allow to disable the JorgsBar.

#### For tool bars:
_enableFullScreenToolBar(True)_: Allow to disable the FullScreen tool bar.
_enablePerspectivesToolBar(True)_: Allow to disable the perspectives tool bar.
_enableQuickAccessToolBar(True)_: Allow to disable the Quick Access tool bar.

Disabling all of these toolbars, the TaurusGui upper toolbar disappears.

#### For menus:
_enablePanelsMenu(True)_: Allow to disable the "panel" menu in the gui.
_enableViewMenu(True)_: Allow to disable the "view" menu in the gui.
_enableTaurusMenu(True)_: Allow to disable the "Taurus" menu in the gui.

#### Others:
_enableSharedDataConnections(True)_: Allow to disable the Shared Data connections procedure.

### CODE REVIEW

**Comment by cpascual** [comment]
I just brought the latest develop to this branch (to mitigate travis issues)

**Comment by cpascual** [comment]
I did a refactoring of the options API and fixed several inconsistencies.

The changes can be tested by modifying the options in the following snippet:

```python
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.taurusgui import TaurusGui

class MyGui(TaurusGui):
    PANELS_MENU_ENABLED = False
    APPLETS_TOOLBAR_ENABLED = False
    QUICK_ACCESS_TOOLBAR_ENABLED = False
    HEARTBEAT = None
    FILE_MENU_ENABLED = False
    VIEW_MENU_ENABLED = False
    TAURUS_MENU_ENABLED = False
    TOOLS_MENU_ENABLED = False
    HELP_MENU_ENABLED = False
    FULLSCREEN_TOOLBAR_ENABLED = False
    USER_PERSPECTIVES_ENABLED = False
    LOGGER_WIDGET_ENABLED = False
    SPLASH_LOGO_NAME = None
    SPLASH_MESSAGE = "Here I am!!"

if __name__ == '__main__':
    import sys
    app = TaurusApplication()

    w = MyGui(configRecursionDepth=0)

    w.show()
    sys.exit(app.exec_())

```

**Comment by cpascual** [comment]
Note that the latest refactoring affects https://github.com/sardana-org/sardana/pull/1042

**Comment by cpascual** [comment]
Hi @droldan: can you check if the changes from b3888d2 are ok for you (note that I disabled **everything** that can be disabled with the new options API)

**Comment by droldan** [comment]
Hi @cpascual, 
I've tested the refactoring and it works as expected, thanks for your job!

**Comment by cpascual** [comment]
Thanks for the review @droldan .
I merge the PR, then.

**Pull request merged**
