### PR TITLE
Fix Bug 343 (support spyder>=3)

### PR DESCRIPTION
**Pull request by cpascual**
Fix bug from https://sourceforge.net/p/tauruslib/tickets/343/

Attempt to import spyder and fall back to spyderlib if there is an exception.

### CODE REVIEW

**Comment by reszelaz** [comment]
I have reviewed this PR and manually tested it with spyder v3.
Since we have dropped support to spyderlib we need to upgrade the taurus-test docker container before accepting this PR.

**Comment by cpascual** [comment]
I just merged a PR in the docker image repo for this: https://github.com/cpascual/taurus-test/pull/1

**Comment by cpascual** [comment]
After some trouble with the docker image build, now the image should be ok, so I retriggered the travis build

**Comment by cpascual** [comment]
I ran `python <taurus>/qt/qtgui/editor/tauruseditor.py` in a taurus-test docker with this installed file and it works ok for me. So IMHO, this could be merged

**Pull request merged**
