### PR TITLE
[doc] Move docs to github pages

### LINKED ISSUE #408: [doc] Get rid of mocks for docs
The docs generation requires importing all modules of taurus for introspection.

This forced us to generate mocks for the various taurus dependencies... but this is an ugly hack which is not easy to maintain (see, e.g. #267).

I see two different options:

a) Move the document creation to Travis.

b) Make use of the now-available [conda support in RTD](http://docs.readthedocs.io/en/latest/conda.html) to install the dependencies using Conda 

I prefer a) because I think that it is easier to maintain in the longer term (we maintain the docker images for the CI anyway), but this needs a bit more initial work since we need to configure the artifact deployment in travis to upload the docs somewhere else.

On the other hand, b) may be less disruptive and quicker to implement on the short term. But I personally have no experience with Conda... so any help would be welcome (@bilderbuchi?  , @pgap ?)

### PR DESCRIPTION
**Pull request by cpascual**
This PR does the last things pending for migrating the doc build and hosting from readthedocs to github pages.

See https://github.com/taurus-org/taurus/issues/408#issuecomment-329782603

Basically it eliminates the mocks and it adds a link to other versions of the docs.

Note: with this migration we will lose the downloadable pdf docs, but IMHO it can be added later on if someone is interested on it.

Closes #408

### CODE REVIEW

**Comment by cpascual** [comment]
@taurus-org/integrators can you please review this?

Apart from reviewing the changes themselves, basically, 2 things need to be checked:

- the docs are served fine from github pages: https://taurus-org.github.io/taurus-doc
- the dynamically-generated list to docs generated for branches other than develop works fine: https://taurus-org.github.io/taurus-doc/v-fix-408/other_versions (this needs javascript allowed in the browser)

It all seems to work well for me... once I get confirmation that it works for others too, I'll merge and ask for the taurus-scada domain to be pointed to https://taurus-org.github.io/taurus-doc/ instead of readthedocs (and we will finally be able to get rid of mocks and RTD other RTD support burden)

**Comment by mrosanes** [comment]
From my point of view, it can be merged,
Nice feature to have the docs in github pages!

**Comment by cpascual** [comment]
Great, thanks for the reviews @teresanunez and @mrosanes .

I am merging.

**Comment by cpascual** [comment]
Checked. It all seems ok now.  Both taurus-scada.org and www.taurus-scada.org point to GH pages

I also deactivated the RTD integration (RTD won't be receiving events from this repo anymore.

**Pull request merged**
