### PR TITLE
Release jul17

### PR DESCRIPTION
**Pull request by cpascual**
This is a PR **to master** for the official [Jul17 release](https://github.com/taurus-org/taurus/milestone/9). Final tests (automatic and manual) should be done based on it before accepting the merge. I've requested review from one responsible from each intitute and protected the master branch so that the requested reviews are required before merging (*) 

Note that the [appveyor artifacts](https://ci.appveyor.com/project/taurusorg/taurus/build/1.0.240/job/68jh7gaqfx79qhr2/artifacts) can be used for manual tests.

(*) This is just for testing this feature of github, which can be handy for replacing the email voting in case of TEPs. If you do not feel like reviewing, just say so and we can dismiss you ;)

### CODE REVIEW

**Comment by cpascual** [comment]
# How-to release

**Comment by cpascual** [comment]
Note, as part of this release process we will try to document the steps that we followed.
We propose to do it in [this file](https://github.com/taurus-org/taurus/blob/release-Jul17/doc/how_to_release.md)

**Comment by cpascual** [comment]
# How to release (draft)

1. During all the development, use the Milestones to keep track of the intended release for each issue
2. Previous to the release deadline, re-check the open issues/PR and update the assignation issues/PR to the release milestone. Request feedback from the devel community.
3. Work to close all the PR/issues remaining open in the milestone. This can be either done in develop or in a release branch called `release-XXX` (where `XXX` is the milestone name, e.g. `Jul17`). If a release branch is used, develop can be used in parallel for other developments, and the release-related PRs should be done agains the `release-XXX` branch. This release brach can be on a personal fork.
4. Create the release branch if it was not done already in the previous step and:
4.1. Review and update the CHANGELOG.md if necessary. See [this](http://keepachangelog.com)
4.2. Bump version using `bumpversion <major|minor|patch> && bumpversion release`  (use [semver](http://semver.org/) criteria to choose amongst `major`, `minor` or `patch`
4.3. Update man pages: 
       `cd <taurus>/doc`
       `./makeman` 
       `git add man`
       `git commit -m "Update man pages"`
4.4. Create a PR to merge the `release-XXX` against the **`master`** branch of the taurus-org repo
5. Request reviews in the PR from at least one integrator from each participating institute. The master branch is protected, so the reviews need to be cleared (or dismissed with an explanation) before the release can be merged.
6. Perform manual tests (to be described below). You may use the CI artifacts (e.g., from appveyor) and post the results in the comments of the PR.
7. Once all reviews a cleared, merge the PR and tag in master
8. Merge also the  `release-XXX` branch into develop, and bump the version of develop with `bumpversion patch`

**Comment by amilan** [comment]
Hi everyone,

I have gone through the commits and now I'm going to start testing them here in Max IV.
I'll come back with some feedback when we will finish.

Regards,

**Comment by LJBD** [comment]
I'll have some time to do the review on Thursday.
If you don't want to wait until then, then please proceed without my review.

**Comment by teresanunez** [comment]
Hi @cpascual, I can not run with this version because of the guiqwt>=3 requirement. But it is fine for me if you make the release.

**Comment by amilan** [comment]
Hi again, 

Just as a comment, I had the same issue than @teresanunez with the dependency of guiqwt>=3. 
I have solved it using a conda environment where I have installed all the dependencies.
I have also installed taurus from the source code (python setup.py install) and I've been able to test the fist point of the manual test checklist (taurusdemo) successfully.

Tomorrow I will continue with the next points.

If anyone has the same issue than us and wants more info about the conda environment, just let me know.

Cheers,

**Comment by LJBD** [comment]
@amilan - if you could send us your environment package list, it would be easier for us all!

**Comment by amilan** [comment]
Sure! I'm going to export the environment, test that it's usable and shared it here.

**Comment by amilan** [comment]
Ok, 
I have exported my conda environment into this yml file:
https://gist.github.com/amilan/cad422bbdeef61a2c41c763240fa09ea

To use it, you need to run:
conda env create --name your_env_name --file=taurus_environment.yml

I have removed the taurus package from this environment because it was pointing to the folder in my computer, and of course, it wasn't useful. To install it, first activate the conda environment:
source activate your_env_name

and then install taurus like it's explained in the documentation:
pip install -e taurus

That should work. Let me know if it works for you.

Cheers,

**Comment by teresanunez** [comment]
Hi @amilan, many thanks. I am trying to create the conda environment ... but I get this error:

Collecting guiqwt==3.0.3
  Downloading guiqwt-3.0.3.zip (3.7MB)
    100% |████████████████████████████████| 3.7MB 366kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-FRyFIo/guiqwt/setup.py", line 30, in <module>
        from guidata.utils import get_subpackages, get_package_data, cythonize_all
    ImportError: No module named guidata.utils
    
  
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-FRyFIo/guiqwt/

CondaValueError: pip returned an error.



Some idea?. The module guidata was installed before:

Collecting guidata==1.7.6
  Downloading guidata-1.7.6.zip (379kB)
    100% |████████████████████████████████| 389kB 3.4MB/s 

Could it be that one have to set something in the PYTHONPATH?.

**Comment by amilan** [comment]
Ok, I saw that issue yesterday, and it took me a while to go one by one installing all the dependencies, that's why I thought that a conda environment could help to avoid having it again.

I haven't seen that when I was creating a new environment with the yml, but let me try with it in a computer of a colleague here to try to reproduce the issue.

**Comment by reszelaz** [comment]
> The module guidata was installed before:

Collecting guidata==1.7.6
Downloading guidata-1.7.6.zip (379kB)
100% |████████████████████████████████| 389kB 3.4MB/s

I think this means only downloading the sources, but the installation did not take place.

Please see: https://github.com/taurus-org/taurus/pull/479#issuecomment-313434830 for the guiqwt installation problem. I don't know how to fix it in conda but locally I workaround it by manually installing guidata first.

**Comment by amilan** [comment]
Yes, Zibi's right.
I thought it was collecting and installing the packages but looks like it's only getting the software in that order. 
An ugly workaround that works (tested in my colleague's computer) is to remove the guiqwt package from the .yml file and after the environment is created, activate it and install manually using pip:
```
pip install guiqwt
```
But as I said, that's ugly, because the main point of having this conda environment is to forget about installing any dependency.

Well, in any case, I'm going to see how it can be done in a proper way and I will come back, but at least, the workaround should work.

**Comment by teresanunez** [comment]
Hi @reszelaz  and @amilan, I manage now using what @amilan suggested.

**Comment by cpascual** [comment]
Just for completitude...

I already faced issues to provide a complete conda environment for Taurus. see: https://github.com/taurus-org/taurus/issues/408#issuecomment-310458330 and https://github.com/taurus-org/taurus/issues/408#issuecomment-310622707 and

**Comment by teresanunez** [comment]
Something must be wrong in the environment, I can not run taurusplot:

ImportError: No module named Qwt5

The tests with taurusdemo run without problems.

@amilan, does it work for you?

**Comment by LJBD** [comment]
A, yes, there's still this thing. There's no `PyQwt` for conda. I'd suggest to use @cpascual's [taurus-test](https://github.com/cpascual/taurus-test) Docker image and there's also a CentOS-based image that our interns created [here](https://github.com/synchrotron-solaris/cfg-solaris-docker-taurus).

**Comment by teresanunez** [comment]
Ok, @LJBD, many thanks. I found actually more errors that could be related to the same issue. I would try as you suggest.

**Comment by cpascual** [comment]
> I'd suggest to use @cpascual's taurus-test Docker

Of course you are welcome to use that, but if the purpose is to test the new release, it would be better to try in as many different environments as possible.

We are already testing in debian9 using the taurus-test docker. It would be better if you tested in a system closer to what you have in your institutes. Similarly, the checklist is fine, but it would be awesome if you tested some of your apps with the new release (this is  a surer way of caching more bugs)

Regarding the Qwt5 problem, in principle you should be able to install PyQt4 and PyQwt5 packages **outside** conda (just as you do in your production machines). And  test with that.

> and there's also a CentOS-based image that our interns created here

Finally, if someone creates a docker image for a different platform that provides a similar environment to that of cpascual/taurus-test:debian9 (i.e., providing all taurus dependencies **but without taurus itself**), we could incorporate it to the automated tests in travis (it would be a great addition)

**Comment by mrosanes** [comment]
Referring to the checks for the manual tests:
In taurustrend2d; the option of save and restore the configuration is present?

Test Save & restore config (change axes range, zoom, tool status colormap etc & check that everything is restored)


---

Others:
tauruscurve and taurustrend1d are deprecated in taurus 4.1.0. The usage of taurustrend is recommended instead.

This two are known to fail in taurus 4.1.0:
<pre>
tauruscurve --demo
</pre>
<pre>
taurustrend1d sys/tg_test/1/short_scalar
</pre>

**Comment by amilan** [comment]
Hi again, 

@teresanunez the conda env is working for me, but maybe because I had already installed taurus in the system ... maybe that's why I didn't notice the PyQwt issue in any of the machines where I have tried. Sorry.
In any case, seems that you can use docker for the tests, so if it's ok, I will focus on continuing the manual tests and after approving the new release I will review the conda stuff.

@cpascual, I also thought in testing our applications with this new release, but in MAX IV we are still using an old release of taurus in production (3.6.0). Our idea is to move to this new release, but first we will need to adapt our apps and that will take some time,¡ but we are on the way.

And coming back to the tests, I cannot plot (neither in taurusplot or taurustrend) and expression like this: 
```
taurustrend 'eval:Q(rand(333), "mm")'
```
It doesn't complain, no error message, but I only get an empty trend ... is there anything wrong in the expression to be evaluated?

**Comment by amilan** [comment]
OK, so far I have tested almost everything in the checklist and the only thing that I don't see any effect is when using the eval as commented above.

**Comment by mrosanes** [comment]
Hi @amilan, I have done the test of 
taurusplot 'eval:Q(rand(333), "mm")'
and
taurustrend 'eval:Q(rand(333), "mm")'

From my docker (and also from my machine debian9), both commands shows curves.
In the case of a taurusplot, a single curve is shown.
In the case of taurustrend, 333 different curves are shown.

**Comment by teresanunez** [comment]
Hi, I have tested what I could. I have similar comments as @mrosanes:

1.
Referring to the checks for the manual tests:
In taurustrend2d; the option of save and restore the configuration is present?
-------------------
I don't see the option and 'by default' nothing is neither saved nor restored.

2.
taurusplot 'eval:Q(rand(333), "mm")'
and
taurustrend 'eval:Q(rand(333), "mm")'
shows curves

**Comment by LJBD** [comment]
> Finally, if someone creates a docker image for a different platform that provides a similar environment to that of cpascual/taurus-test:debian9 (i.e., providing all taurus dependencies but without taurus itself), we could incorporate it to the automated tests in travis (it would be a great addition)

@cpascual -  I will adapt the image we have so that it has all dependencies and no taurus and I will get back to you with that.

**Comment by cpascual** [comment]
@amilan 
> taurustrend 'eval:Q(rand(333), "mm")'
> It doesn't complain, no error message, but I only get an empty trend

The problem is in the space after the comma. It should be :
`taurustrend 'eval:Q(rand(333),"mm")'`  , instead of 
`taurustrend 'eval:Q(rand(333), "mm")'`

Sorry, it is my fault. I wrote it wrong in the examples. Now it is corrected.
And in general, in order to get  more debug info, you can use `--taurus-log-level=trace`

@mrosanes 
> In taurustrend2d; the option of save and restore the configuration is present?

No, there is not an option in the menu, but you can test the feature by creating a TaurusGui (e.g. with `taurusgui --new-gui`) and adding  a TaurusTrend2D. When you close the gui and reopen it, the settings should be saved/restored

**Comment by mrosanes** [comment]
With the space after the comma; it also works for me in debian:
```
taurustrend 'eval:Q(rand(333), "mm")'
```

In windows7 64bits, there is a problem for 'eval' scheme related with single and double quotes:
This is accepted:
"eval:Q(rand(333), 'mm')"
But not this:
 'eval:Q(rand(333), "mm")'

**Comment by amilan** [comment]
Hi, 

Thanks for the reply. I've been able to test it and it's working fine.

PS: I'm speaking about the linux version, I don't have a windows machine.

**Comment by teresanunez** [comment]
HI, I had not done a copy/paste but typing ... this is why it was working for me ... I wrote it  (by chance) correctly. My tests are also only in linux (debian).

**Comment by LJBD** [comment]
I have an organisational question: should we create an issue for every little thing we encounter?
I've started creating issues for the errors, but I've just noted smaller things in [my Gist with the checklist](https://gist.github.com/LJBD/7ece56050ffcf78e8b1dda15c1d63d4e).

**Comment by amilan** [comment]
@LJBD nice idea the Gist notes.
I would say an issue per thing that you found, but I don't have a strong opinion on that.

**Comment by cpascual** [comment]
> should we create an issue for every little thing we encounter?

I would say that the gist is an excellent way of having some personal notes to which you can refer for discussions... but if/once it is clear that something is a bug, then the best is to create an independent issue  (or even better a PR!)  ;)

**Comment by LJBD** [comment]
All right, I will go through my Gist again next week and create the issues.

**Comment by cpascual** [comment]
Hi,
We did our tests here with Debian9 and with win7 and, although many things came out, all the "release-critical" ones are already solved in our opinion.

The rest of you that are doing tests, do you see anything "release-critical"?
If not, we would go ahead with the release today or tomorrow.

**Comment by amilan** [comment]
Hi, 

In my case I don't see any release-critical issue, so for us it's OK to continue with the release.

**Comment by LJBD** [comment]
I haven't found any critical issues during my tests as well.

**Comment by cpascual** [comment]
Thanks to all @taurus-org/integrators and everybody else who contributed with code and/or bug reports to make this release on-schedule!

**Pull request merged**
