### PR TITLE
Taurusgui config

### LINKED ISSUE #918: Modular loadConfiguration method in TaurusGui
Hello Taurus Community,

Right now, `TaurusGui.loadConfiguration` method is quite monolithic. Different elements are loaded in one go. It could be split into different methods (maybe private ones?). Thus would allow more flexibility with managing configuration options and adding new ones.
Another benefit is that it would be easier to get Sardana stuff from `TaurusGui`. Having Sardana options in different method(s) would allow to easily move them to Sardana version of TaurusGui (no need for `MacroBroker`, just inherit from `TaurusGui` and add new behaviour).

### PR DESCRIPTION
**Pull request by stanislaw55**
This PR provides modular `TaurusGui.loadConfiguration` method. Now it utilizes set of `TaurusGui._load*` methods for modularity in loading configuration. Also, sardana related configuration options are moved to only one method `TaurusGui._loadSardanaOptions` for easier separation in future. 

Tested with `tgconf_example01` and `tgconf_macrogui` with Sardana version 2.7.0 (from pip)

Closes #918 and issue #62 can benefit from it (maybe even can close it?).

Please review, test and provide feedback.

### CODE REVIEW

**Comment by cpascual** [comment]
Thanks!

I'll have a look at it ASAP. I mark it for inclusion in the next official release (Jul19)

**Comment by cpascual** [comment]
Hi @stanislaw55 finally I could start with the tests of this PR, but I am getting an error when testing with tgconf_example01 (reproducible with both py3+Qt5 and with Py2+Qt4):

If it works for you, can you check if you forgot to push some changes?

```console
(py3qt5) cpascual@pc218:~/src/taurus(taurusgui_config)$ git status
On branch taurusgui_config
Your branch is up-to-date with 'solaris/taurusgui_config'.
nothing to commit, working tree clean
(py3qt5) cpascual@pc218:~/src/taurus(taurusgui_config)$ taurusgui example01
MainThread     INFO     2019-06-12 20:10:08,628 TaurusRootLogger: Using PyQt5 (v5.6 with Qt 5.6.2 and Python 3.6.8)
MainThread     INFO     2019-06-12 20:10:08,833 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/icon/)
MainThread     INFO     2019-06-12 20:10:09,390 TaurusRootLogger: Plugin "taurus_pyqtgraph" loaded as "taurus.qt.qtgui.tpg"
MainThread     INFO     2019-06-12 20:10:09,404 TaurusRootLogger: Starting execution of TaurusGui
Traceback (most recent call last):
  File "/home/cpascual/miniconda/envs/py3qt5/bin/taurusgui", line 11, in <module>
    load_entry_point('taurus-legacy-cli', 'console_scripts', 'taurusgui')()
  File "/nfs/home/cpascual/src/taurus_legacy_cli/taurus_legacy_cli/taurus_legacy_cli.py", line 382, in taurusgui
    configRecursionDepth=configRecursionDepth)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/taurusgui/taurusgui.py", line 346, in __init__
    self.loadConfiguration(confname)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/taurusgui/taurusgui.py", line 1032, in loadConfiguration
    self._loadGeneralQtSettings(conf, xmlroot, confname)
AttributeError: 'TaurusGui' object has no attribute '_loadGeneralQtSettings'
```

**Comment by stanislaw55** [comment]
Indeed, I just forgot to push those changes.

**Comment by cpascual** [comment]
I finished my review and IMHO it is ready for merging. I updated it with the latest changes in develop and I added a fix to #570 which is also related to making TaurusGui more flexible. I'll merge it when the CI tests are green

**Pull request merged**
